apiVersion: v1
kind: Secret
metadata:
    annotations:
        argocd.argoproj.io/sync-options: Delete=false,Prune=false
    name: grafana-admin-credentials
    namespace: monitoring
stringData:
    admin-password: ENC[AES256_GCM,data:/6X5QowHk7tPUU9CVfYtaULPMse1RQBghMuX0GIVbeM=,iv:xdU+JqtPiRGpSd6FRLF0eA75Ld+iCm1oUNKQi5JLU0g=,tag:V0eTq5sM/Mcn/B7IV8QYow==,type:str]
    admin-user: ENC[AES256_GCM,data:Iat2bmU=,iv:nRYCRstdr/1n38jVbThWikaf9VApY/zeaj0IMQe7cbU=,tag:LGqCuhadr+EJ/WMY/zNmGQ==,type:str]
    discord-webhook-url: ENC[AES256_GCM,data:sZB4VOywpYFmaZM78ghL5YqByjsGzcektsSK9XNUJQMqGqto8WKJj1lm5kKf9WGzkugK0zN+MNOlTAmhu4K9MpWgKvMzqqQjUparLeIolkr9FPtDYG92Fz/qK2fyyOc7/aNIU7i2Hfb3QqB/GtepfMgX/j+4vKvU8hRxNw==,iv:s+nt3nyZVy9pAuZkZQtypMeEzGL4aghxX4UIkpL37AY=,tag:l5W0cVZPb3Fio3IvYrbQtQ==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHODR6T1pjM0tvWGd4bDZ0
            WWRFSitrZXhwbVU0Q1NDYll3cDZvOW9qeVFvCklDak9hSFFTN2FvYndUSGVkV3Yr
            NVlEMW5CeTJBUzgzTTJvQmYxbzhKSlUKLS0tIG9neVNtYWptTmZwRXRUYVp2cU9y
            NlhKWjJnNEhJNEdzSE43WXY5VWtxbk0K7D+shRU/dboDFpItu0Wd+vubxrYxgJzq
            9ZgpsQw8liiwmXhB2OQmgzpn5+B1h5oL5wrny5wj089oaRI2WzwpZg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5wsguw34gmnnllle8qzcjvjkl22e88em3a0lseqs0l9lscmr5pqsg6gyn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Zy9JbkUvbC9kdCtZTWdR
            MmF6U3pEaXAwemk0akQyMWJVSG82OURGSTBFCjUvdjRnbTlYSklicXh1dUFkQVBJ
            b0tFV1REWjRMbEo3WHlKbEkxOEUvSDQKLS0tIHJqZnVwVVNjRnMxRmQ2d1pXeWdr
            UHY5UVM2YTliVHBGcWRqTlJNVko4MkEKryz53C+84GYI0d/rEskSUS1WsLVWdoCu
            HrCiikcDIsnUa2WeY9pMICC0JDqhlwu5rnb23bjEpW9ffOB6X3+Drw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13yvwrz6cvg8cwq78m6jvy9mndjdyuv0k3kh0du72v28puqcuafms8p28gr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T13:34:55Z"
    mac: ENC[AES256_GCM,data:2OAWj6MHQdJSLnHIjrem+FN1KbJJ2VeNI0X2qp7VTM2RWX4uJq7Kh7VDJHlLDl5VrZShe+kbH9E6oydwduuf28uueoPo8NHngfhxRRtmu/B2wvfoTnGuD2UU1Y1zkWPJNQYpsBHj0ucGeOvjGqC1snY1Vzd06UcYrg4Mfb/VXjE=,iv:5A3FEsfKjt/Du4H8OrlTi3DFBNYJI7qyHoZcCq0wxvg=,tag:bwurhkj84ZC99+AijiiXAg==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        argocd.argoproj.io/sync-options: Delete=false,Prune=false
    name: grafana-dev-credentials
    namespace: monitoring
stringData:
    username: ENC[AES256_GCM,data:eH5pnJFAUto=,iv:KnFWdBiUeHgFmcc0qnUS39Funi/pViUyhcZNjwakQOs=,tag:1+kXHDL0zla4YYgYIJ1yiA==,type:str]
    password: ENC[AES256_GCM,data:1oBvFKsRgHS6bUuIGWKNI1GKmBQwcNr5m2NXhV+pM6n8zPKHhq1ITw==,iv:Kmxmy7tFMVBhv+9pxYKxDNgyAaQCNuJfHRWsEnzuNE0=,tag:Yac7V++mgrUuPhrUyqVTWA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHODR6T1pjM0tvWGd4bDZ0
            WWRFSitrZXhwbVU0Q1NDYll3cDZvOW9qeVFvCklDak9hSFFTN2FvYndUSGVkV3Yr
            NVlEMW5CeTJBUzgzTTJvQmYxbzhKSlUKLS0tIG9neVNtYWptTmZwRXRUYVp2cU9y
            NlhKWjJnNEhJNEdzSE43WXY5VWtxbk0K7D+shRU/dboDFpItu0Wd+vubxrYxgJzq
            9ZgpsQw8liiwmXhB2OQmgzpn5+B1h5oL5wrny5wj089oaRI2WzwpZg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5wsguw34gmnnllle8qzcjvjkl22e88em3a0lseqs0l9lscmr5pqsg6gyn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Zy9JbkUvbC9kdCtZTWdR
            MmF6U3pEaXAwemk0akQyMWJVSG82OURGSTBFCjUvdjRnbTlYSklicXh1dUFkQVBJ
            b0tFV1REWjRMbEo3WHlKbEkxOEUvSDQKLS0tIHJqZnVwVVNjRnMxRmQ2d1pXeWdr
            UHY5UVM2YTliVHBGcWRqTlJNVko4MkEKryz53C+84GYI0d/rEskSUS1WsLVWdoCu
            HrCiikcDIsnUa2WeY9pMICC0JDqhlwu5rnb23bjEpW9ffOB6X3+Drw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13yvwrz6cvg8cwq78m6jvy9mndjdyuv0k3kh0du72v28puqcuafms8p28gr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T13:34:55Z"
    mac: ENC[AES256_GCM,data:2OAWj6MHQdJSLnHIjrem+FN1KbJJ2VeNI0X2qp7VTM2RWX4uJq7Kh7VDJHlLDl5VrZShe+kbH9E6oydwduuf28uueoPo8NHngfhxRRtmu/B2wvfoTnGuD2UU1Y1zkWPJNQYpsBHj0ucGeOvjGqC1snY1Vzd06UcYrg4Mfb/VXjE=,iv:5A3FEsfKjt/Du4H8OrlTi3DFBNYJI7qyHoZcCq0wxvg=,tag:bwurhkj84ZC99+AijiiXAg==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        argocd.argoproj.io/sync-options: Delete=false,Prune=false
    name: grafana-staging-credentials
    namespace: monitoring
stringData:
    username: ENC[AES256_GCM,data:V+tjebsmgSWR/gM+,iv:3W84t3rZAyjP7fg9nVlMae/7t4ECYagqDxsvpoVK31c=,tag:/SJgw5gs4inSw/ORJU3MXA==,type:str]
    password: ENC[AES256_GCM,data:p4n9vVRrlg1rbTe7AxQH+WRaFOiKhzki3PTYBiJeKnP/Tg+qWlMarQ==,iv:ySQvqRQjK8978fFtv/5W0A2TIHnThhIBJCLpYUxKtYo=,tag:i6uiLI+YLRUerC1TcfQovw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHODR6T1pjM0tvWGd4bDZ0
            WWRFSitrZXhwbVU0Q1NDYll3cDZvOW9qeVFvCklDak9hSFFTN2FvYndUSGVkV3Yr
            NVlEMW5CeTJBUzgzTTJvQmYxbzhKSlUKLS0tIG9neVNtYWptTmZwRXRUYVp2cU9y
            NlhKWjJnNEhJNEdzSE43WXY5VWtxbk0K7D+shRU/dboDFpItu0Wd+vubxrYxgJzq
            9ZgpsQw8liiwmXhB2OQmgzpn5+B1h5oL5wrny5wj089oaRI2WzwpZg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5wsguw34gmnnllle8qzcjvjkl22e88em3a0lseqs0l9lscmr5pqsg6gyn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Zy9JbkUvbC9kdCtZTWdR
            MmF6U3pEaXAwemk0akQyMWJVSG82OURGSTBFCjUvdjRnbTlYSklicXh1dUFkQVBJ
            b0tFV1REWjRMbEo3WHlKbEkxOEUvSDQKLS0tIHJqZnVwVVNjRnMxRmQ2d1pXeWdr
            UHY5UVM2YTliVHBGcWRqTlJNVko4MkEKryz53C+84GYI0d/rEskSUS1WsLVWdoCu
            HrCiikcDIsnUa2WeY9pMICC0JDqhlwu5rnb23bjEpW9ffOB6X3+Drw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13yvwrz6cvg8cwq78m6jvy9mndjdyuv0k3kh0du72v28puqcuafms8p28gr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T13:34:55Z"
    mac: ENC[AES256_GCM,data:2OAWj6MHQdJSLnHIjrem+FN1KbJJ2VeNI0X2qp7VTM2RWX4uJq7Kh7VDJHlLDl5VrZShe+kbH9E6oydwduuf28uueoPo8NHngfhxRRtmu/B2wvfoTnGuD2UU1Y1zkWPJNQYpsBHj0ucGeOvjGqC1snY1Vzd06UcYrg4Mfb/VXjE=,iv:5A3FEsfKjt/Du4H8OrlTi3DFBNYJI7qyHoZcCq0wxvg=,tag:bwurhkj84ZC99+AijiiXAg==,type:str]
    version: 3.13.3
