apiVersion: v1
kind: Secret
metadata:
    annotations:
        argocd.argoproj.io/sync-options: Delete=false,Prune=false
    name: upayan-web-env
stringData:
    BOT_TOKEN: ENC[AES256_GCM,data:YcpfNDhjN4ul9tnxxN5/CAMUX9G/XvL5Dw9lpqgFQPjngTo+1AtwaNCGEjjhgDXEkw+jEwpNEJdwMuS7jspmup2UUoUTU0j9,iv:Dx04ar+/x6us4+lmnKpU6SnmrJ1Ir7d0Xc65SUjcZ/U=,tag:8ogJF5mBtBolquGF/OGZOg==,type:str]
    CONTACT_WEBHOOK_URL: ENC[AES256_GCM,data:hPOXH2t644H0Uzxk4s9Ard8JPvr/a/udGv7kuIyc6jIMu1vlufCTwvooaYGkazydOsX+E/Vj7+vSzDXA7i6U+EZfxC2bSvBQ5fG1lOO5kVY632aROo2Fz+W5rLlUzj4D8BEHHy4Ub1VklOv+eFF9JcAitlOXqTmjMw==,iv:2WhzlZltUkgB9Vs2VBDt6EUXiao7aNOoTU0UAZ0J8AY=,tag:7CSm6Gl4CoDNDei7a993Ew==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:VzUeLPd+n6bRxNtpgcwS8R/fqcvabtF2VWno7We6LKyNXUiIhxPKpbHq6KQzEAFArtKg7Tw4ZQ6N/1eRUVrcE1l+m7iMFBrvReL9eHBy+WYd9WYt2H86bIhRBVzT,iv:WaVMujxzuEjal7XbhAZ3xKoQbG03Ln0NcO6cG/V2Gbg=,tag:eX7Tiei4WUQQVXhsmDYVzg==,type:str]
    NEXT_PUBLIC_ENV: ENC[AES256_GCM,data:GzvPyIKzKEHOSw==,iv:Y0RBCjOXk+ESq/O2ZskNKe5wNb4u3EHh6rkQpoZAbEw=,tag:Fbdfs9rgB6/TGldK+bfyKQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwWXZCRExpUlBQamc0b3dq
            ZVlSeWk3YlQxVFZocUtRNDZOY3JqSW1Zb3pJCmtiTmNuWGVHSzB3OUdPQTdBWkVM
            QWtHdHc2ZHpmMnBVbTZsZ1hpb3BMVkUKLS0tIDN2RllvSTc1VVpnTGFxU2ZvUlBX
            QmFKSUFYNENrTXoxTGtwR0EvcTdVdXcK18OXNXaoAKgA4DKfjCJA4qg1lYb8vy3B
            0H1IQBJ3Q1VgzvklXvpUMCMBMiFy5/KtqQj6I2V+KpH/yrv/NXO2jA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5wsguw34gmnnllle8qzcjvjkl22e88em3a0lseqs0l9lscmr5pqsg6gyn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTbDZKYVZqaWZFaEFYT3lH
            WWlSRjBkNkhzMmdkRkhGaFdiclpPQ0sxa0dJCjdhMnZabVd6OW1UcGo1NmpncVBW
            dTFkbkwwaWNUMnk4UExkbEl3OTRnQTQKLS0tIDBBTjVSVk4yN2pPK01NQmJYVTdO
            Rk9BMGg4MEJHS3FJd2svaXFWR2svYU0KFZtpVujlY79ecgdEZEmR5861oqMBn4bY
            30igPf6QErqj+yJQF9F+B++6+PlYOUvPJHWmArh8Htx/175c/gHjnA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13yvwrz6cvg8cwq78m6jvy9mndjdyuv0k3kh0du72v28puqcuafms8p28gr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-28T20:54:39Z"
    mac: ENC[AES256_GCM,data:AW+wZ5IYfL0wNYuZITVT13g1bN63cXugZr+SQVOA9ZJxR2a1R0GloOfN+tsGoswt60UEi5Zka1k+IKP87pBAPf8rCbbM5j9lGJLI1feRfYMKO0iOUdowZuwGn19J97iNmlhTLmySXLVhH0Ovq9V+dF/hrUBQ222za3jkRU7KT2w=,iv:heDCLjoaRbwWCYicBONiFtmOb7ZMaXEh/MG8FFkFQWs=,tag:KyBjEi73rHzowhTTr+s6Uw==,type:str]
    version: 3.13.3
