apiVersion: v1
kind: Secret
metadata:
    annotations:
        argocd.argoproj.io/sync-options: Delete=false,Prune=false
    name: kodesphere-env
    namespace: kodesphere
stringData:
    API_PORT: ENC[AES256_GCM,data:w7Lhmw==,iv:oMkB7KdXCD8AZOQQlijy5syJAiTIsoGUwTqFkrdXSyw=,tag:sS2O2e7is2Yn/AA9qQlfSA==,type:str]
    GITHUB_APP_CLIENT_ID: ENC[AES256_GCM,data:8Z54sHeACTJgYTO70q5c0df7VtQ=,iv:80djgpm5LEJUmQcCHZ4iRN67o5kkiuP5/ok0HAuxpws=,tag:VKq7O6dfZwuAHDZ6VBVn6g==,type:str]
    GITHUB_APP_ID: ENC[AES256_GCM,data:w2mlWtc2Cw==,iv:bbQpwW7BY7Ax4ZK0KTp5fNLZVeOf8Zfg+w+YR+vtUhM=,tag:s9GeM43TIVwSj84jpuo6KQ==,type:str]
    GITHUB_CALLBACK_URL: ENC[AES256_GCM,data:vTSDe/Ag1f5YgHF1mbEH2EBMh5nx0hpF+A==,iv:3OUJic1bKA+yO/GbQTQgRhLzIQu4MwlV/YDihTQPfNI=,tag:r9NC8ZCCq2JKhlxK1t3vEg==,type:str]
    GITHUB_CLIENT_ID: ENC[AES256_GCM,data:QV/CkOtdD3oa8OqGDLfcLR3Ooeo=,iv:kbfUlJxFSNZIPP+xR7gtTaxEgkp70nzp+DqX8KRZzDc=,tag:fQkkSOw6kFeklSEjRARjmA==,type:str]
    GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:G+5tSntO7NclXvoeENGpdfXkklisljRl6ctndk6J4jemFqa5zj87ew==,iv:WlGiLkzwRTg7fvrZNm553QNjghIoqpVkudwdC66jklw=,tag:wsGCusAV7fCBRVtuLMTnfQ==,type:str]
    GITHUB_PRIVATE_KEY_PATH: ENC[AES256_GCM,data:TVACheVbrp2GB/unK2vC4KK0CmTzkKODd8CAfnnJEw==,iv:RTMejjkAHCpE2ENc7a4Kdd+424jsxZaXeFiE74lRH7A=,tag:NfJhojLbHY7aNT+3TnQQLw==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:ZQwWAvlNjyO1/3nYIxpoCMpJR5BpmwxZYfd0mNGMR1A8Vz5K6XzDq0HHq9Yym5JtbYaVHqQVGQYAAQh6+FfC5G0gg95CPC/YJPIhCuGhGnc1xInk6RFyRRLtk3Wj,iv:dfcJiubzgqWOGTGfuJjidUDC+K+A2KQnEpGthDPQ9rM=,tag:hNQsjaoajVm075hiiqUotA==,type:str]
    MONGO_URI: ENC[AES256_GCM,data:dSkRdZYTswyNjJnwfNUhREnKTy6GEJ0ZxF6oqj6Nu14aNbN/MneAluSDkOEpzQa0qlc+dtnt8juXjVffKDnqjC7SOMENdMsTdm4up6AW1x/9teDpiwVuB+xA/t3VlJYAACi9MUo6MDecyaeF9oD8eali1S8G,iv:BzDsbVXoqcpN8P09JpHKgpxlNe7iTXEgIoJ4FMyrn4k=,tag:Sa0c6TwvJBTXbYg4+Vcynw==,type:str]
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:t6XHD5OtsIVx1wLF66oZatCucUOPTpkW7Wwg2c1jpDqx2CzRUvqWMgT565U=,iv:AQnEyYxM1O+6q9LPKM+VMgo6JGvVIR+3UC3cSXkDgkw=,tag:EzYk25kXkLvgVqI4y4pWww==,type:str]
    NEXTAUTH_URL: ENC[AES256_GCM,data:5YALhL8hjEgT5+nEmT0qoxA+mBFPbw==,iv:inLvQzL5zacSdkIN73p/rl2+eSK+W4T0+rWsRFg3D/Y=,tag:awSZXKPkd/QwHFMetT86dw==,type:str]
    NEXT_PUBLIC_GITHUB_APP_INSTALL_URL: ENC[AES256_GCM,data:SBq+BzprDyXxufov6t4CK6HZbEaGN0Ux2MHEeYEE1+lVKulKoXM=,iv:6qyXDG5UNRlgKc3YRHVWq0Vpuj0VNlJPG21TlK0IM9Y=,tag:X6gUM+9YTnzNHeGzP4+W0w==,type:str]
    NODE_ENV: ""
    PERPLEXITY_API_KEY: ENC[AES256_GCM,data:a/pSeVnjhYo+2xDCuOKoCRCXb8bPl4uKyTebEHCh6CwZDQ+D8Hfdtsi+NagEtA8TF3QRyYA=,iv:7GVxOaqlL5zgOBRzBfYsFk2r43tLZtVzLPFK17v5hgY=,tag:pz50Ql1VFWAyd8vpXOMtBg==,type:str]
    SESSION_SECRET: ENC[AES256_GCM,data:7DgDsZ4Dx1nz7suucmdXqsqJdSuvvb39QAW4vj6gviYY8AlMfVEQ5Aa7htk=,iv:0tpQqcB1tjwP/jiK0rUlLynxczDNEQg1p+ipBrK9O7o=,tag:O/NFylJzLZwMrvCYu9AKIA==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhUkpBS1h3aTE1enpKaGU2
            bE4ydGxId1hKdlN1QnJheVZLdWxVNXprdkhFClhyQjdlcWJTVzhUOERDS1hHMXZF
            MC9GSWxQSDdMZm8zVEtFNWNlekdTVkEKLS0tIE9FcjFFTmxqUG1qT3B6K0xNM0Vh
            aHIrcS84SWJFOVV3VnpSR2N5VURURDQKex8stW8L4yVy5wPH8utT2FCnlzIaelyV
            uufXpVtenUoug7sbHYiod63hpd6lBO9WcaQ4mQv0oijFbXjvMXvxlA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5wsguw34gmnnllle8qzcjvjkl22e88em3a0lseqs0l9lscmr5pqsg6gyn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlajgxUXY2UjBkeGxOa3hr
            K0dURC8xeFFXUFNOa0hFZzVxcmxwODBkSlJnCmhLRDRKSWk1YXBIMnNjS2o5YmlT
            d3FUWmZ4YWFOMTZxMjBsbHY4L0ltRmsKLS0tIHlORW9KbXcvSHc0MXhpc2ppaklJ
            ZEZCMi8zRDVsR2xhRk54ci9wUkNJeFkKTCrabz37QxCTX5gQHbDWza1TfClJjSdA
            v5F24dU/4hK2BHnpITrr0fPES33RCt+RJnvT2CptND9+Q3dX0sz6lA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13yvwrz6cvg8cwq78m6jvy9mndjdyuv0k3kh0du72v28puqcuafms8p28gr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-28T20:54:39Z"
    mac: ENC[AES256_GCM,data:r7L3e7YRnSp1ezqJURQZkZFCcnQOWELeGvKXKLPU2OnTXHxrowUGC+6PnXui5JfVxLrupCtGZ8n+92/1oX2tNAMAmEKcNSX1osCfDdzuNa0oYFSwRzMImSadY4RoAezJF9qEn7p3fMPpmGJ5EmwL+hKPxeA9BI1QsGqiwBq6m54=,iv:5hUUST5aG0bNT7cTKPZc9V1G6rSlBBSF9PqnMohMaRA=,tag:+b1cuSTx3O7dHcLj4Ycy0Q==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        argocd.argoproj.io/sync-options: Delete=false,Prune=false
    name: github-private-key
    namespace: kodesphere
stringData:
    private-key.pem: ENC[AES256_GCM,data:wL58RRuRFCCRCfDmFs/fuFkoRWTOUB8vL9a22keC6q+onYOVbC9cimggpqXq/GQp1YmeFJ4q8LIvic106xeEW+b08xiJXNqsgaBaFltgjxa1O/UfUnt0y6oqS4zQltnJpyj0xsjZcE33g3gGNv5541iUL/srSCKBpRX0rzwgryeq9xxFhvwJSPE40Zdsu0Z7kxiJ/JOOwu31vQEHEncWEFS5UMJN1Ek2fF7XvkFtAdnkhbMB/o2awOJ92yfpSo9yrhVhsYWwg+ZCllLyByTf40nLUeIGtMUPXKJtzcki4oEbgT70sJ6NTROZDjPDmeYjqhIvJ6AvVa0YvfB/LNovnh+3Ug9VtCvk/k8XadlXWNl3J3b2c+CLhLFbg7F54d/nzE4DZjFGZAdqm3sO8i99NyAhseAludE0psvNujs1qBA+btrWuIiHBqQA3FQHKqrRXod+/0+Vg/1nvVTlJAJsl/aI9+t+yUHD9g4VFl0t/RuTalqhyo71BkiKEARiNMkfv4Mo+7Wjd+vyUltot0khPSKeoo4VvHVN9X72K5I7smEotwrhDu6QTViiscbXZkpORdJSUJ+kdGR++S6GwKY50cyBU60GtKFRUO8dRXRxxdNqy62fKL8/N+nkCmWHbhB/HakG3fusNYB6X6ZzsM1TWjMSzcs4CAZ94sGvL9Bn+Z9bR5ds4ogILz/nmA8ZqucpfyUkWyu15uY9kA3b+Zm11FsEdycn41C7J7qN8aEAuku06OooAUvjGtCe7C6aTVYpG6QIwdxLp7I/LQ60/063FpDBmcRGyxBoEk9W9Z3EIG6QtzSWZwj4/ANEmcxE9hBvnWrIY4rEeOgUMFc834OUE4d9uyymG1HpNgStrnSaYO1KdmtymZ9hlWDwyVGJ6rMkaDbIcvClmLajI2OssiPNQar2LIeHy7U2PjIE/B3+ROnGdQRuW7GPkNYOMXoHeQi5BcPlCH6HzQ0Btt8ZKDFsW/3yMvYNfQAqEY8oZNyqQXaBoSEeByDjWvlSjfrHJAPQoXrmkSRzTvhblWuM+sbd8AwRIzXkTrvuUUSPtl0efUhckKW2RUEYkuTHv0eAmEDdD4VN7JC6EyDkxcUT3AzJmiNFjBWISGrROfBPf4Ry+q5I8kPTVTMI0UcDi4Eb685U8HJMs3QGERjZqqJyrZDk2msj/VdTZxtr30+TI8cS6Z0PyaNXBk6BlmQeFK0N9GmlFjpRXKyCpF+QgzYP7dvDrLwhIGR7tbr/NFU/BUNHy+fVh9gHSysWuPgAETiPd8e2Y9z+SQW3/bnhSwqK9Eh3uRfGujWBkm+OjfG4zhIne4vGVeWO9A75F4BDvmyZeMpA/YS6ymgtyWK6vkYAbH0IB1bRDhixJBrEdGeH40msdlAMoI8qiATaN/m1wrjU4tCdsYKqI2P5BsK2CTl1CB60xR7Qdu0eiDS1rIdp578vAbv+6xq4geC/PAPnlu0Emgx0zLiAX1Qs0YXwpPCQHhBWaRoQsdFDvm0kXGkfijs/Bf/GxwaGcUXMAMffcxzrsssYv726FzT3x5HplPuKhUl4D9fiPMSzw5R0k4PYNeg/3U8MNdGJ4kDewif4vK1qozBJbvTPGXzj89rfpJnfe05VfKnrKsbhuCjQiKA1ZAbPUkNJMK7uS0gkSiPNMUrZzVxSHmNKOA1Qh4+LLIgBGeVtl/oB+QgIFiGJEoB4baYU0W9dci2+IPhhi/aQ+Jyrj2FexOWS6s9oQAq5kEUX7cojUPEYBwlY++unoqm1hRHDeIA/rURh7mbtUbbnHxEIaziEnUo6XwKENlTqJmRWEehE9b+mAIp3+S8Xr3oouHTZq0+YLG3UCPrfgbJW3KBMaChpQq84xCAGJS9an0Ey/43owultgtrFQx4n21ED9/Pa0vvr7AwhjsxQUnHfGqaxNYYEAeSRZW+6DIujK9CKZsFCoPDr31uVJf5iyzVfauxzG/rW9HPbsj0rYrOmYPwzk5dWRoXTt+uMI90e5wrgJf/Dw4eeGiy8Y+4+XnDmFJxh4sa8KE/Dx61jZGbA3TGjez7jr51BNqcSFDIGxQPchEmhad4WhOwhTe3atRJWCEF0Y6zWjf7nqmEPmvb5AcpnF7QnSqvgcC99EQKNjs0Q2MYw1u63ZQvxKHHCTeug41/mQ07oXXoUFKJ/jDGPyl5bDKNKckZbye8QmTEFKnUwuUDE6icj2NlUSZ6Srh+7o6XqiNhjwmp++Oz/OjAsyWWqaQw=,iv:eTGsW3zJUMesjGhZJHeOoNgBOgXfvbrLK1QuFuFkI0E=,tag:ptmEvTO96RAErgejtR5l3g==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhUkpBS1h3aTE1enpKaGU2
            bE4ydGxId1hKdlN1QnJheVZLdWxVNXprdkhFClhyQjdlcWJTVzhUOERDS1hHMXZF
            MC9GSWxQSDdMZm8zVEtFNWNlekdTVkEKLS0tIE9FcjFFTmxqUG1qT3B6K0xNM0Vh
            aHIrcS84SWJFOVV3VnpSR2N5VURURDQKex8stW8L4yVy5wPH8utT2FCnlzIaelyV
            uufXpVtenUoug7sbHYiod63hpd6lBO9WcaQ4mQv0oijFbXjvMXvxlA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5wsguw34gmnnllle8qzcjvjkl22e88em3a0lseqs0l9lscmr5pqsg6gyn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlajgxUXY2UjBkeGxOa3hr
            K0dURC8xeFFXUFNOa0hFZzVxcmxwODBkSlJnCmhLRDRKSWk1YXBIMnNjS2o5YmlT
            d3FUWmZ4YWFOMTZxMjBsbHY4L0ltRmsKLS0tIHlORW9KbXcvSHc0MXhpc2ppaklJ
            ZEZCMi8zRDVsR2xhRk54ci9wUkNJeFkKTCrabz37QxCTX5gQHbDWza1TfClJjSdA
            v5F24dU/4hK2BHnpITrr0fPES33RCt+RJnvT2CptND9+Q3dX0sz6lA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13yvwrz6cvg8cwq78m6jvy9mndjdyuv0k3kh0du72v28puqcuafms8p28gr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-28T20:54:39Z"
    mac: ENC[AES256_GCM,data:r7L3e7YRnSp1ezqJURQZkZFCcnQOWELeGvKXKLPU2OnTXHxrowUGC+6PnXui5JfVxLrupCtGZ8n+92/1oX2tNAMAmEKcNSX1osCfDdzuNa0oYFSwRzMImSadY4RoAezJF9qEn7p3fMPpmGJ5EmwL+hKPxeA9BI1QsGqiwBq6m54=,iv:5hUUST5aG0bNT7cTKPZc9V1G6rSlBBSF9PqnMohMaRA=,tag:+b1cuSTx3O7dHcLj4Ycy0Q==,type:str]
    version: 3.13.3
