apiVersion: v1
kind: Secret
metadata:
    annotations:
        argocd.argoproj.io/sync-options: Delete=false,Prune=false
    name: bandit-secrets
stringData:
    CUSTOM_DOMAIN: ENC[AES256_GCM,data:nuCeuYLfZghxF8Sm8v5mn910Fnd+YJQIug==,iv:0Te3Pc21o/w2HMoJA8t6l7Z+KSCntAcgkcQdc0/e6Sw=,tag:HHsfUVHo3eNm5hKAwNQEGg==,type:str]
    FRONTEND_URL: ENC[AES256_GCM,data:vARFpEt8giD7LhxX7mie/zHf+fq4b+lOmg==,iv:EYAu8hPNwpHHgl9MypOkv2JICFsyjp5ekyK3TWkOJp0=,tag:8L2KAmhDx1+0gRVsRY4Zag==,type:str]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:g8ua+Hy9qOVOlPplMD92LYbcFYxy+Puo/u37wXpgBnxhrFGGSpqmG6xjHOr1+519aB6j+T+UPpXCWgmHFyI7lfqKDY2foVrz,iv:e+zyzAOJtvNF24OYJKGiJev96kqmfcITzWW72uluRNg=,tag:2BvtK1KKmeOlru7XVLZjxg==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:c041NJQ8HPqYijv8zqV5HRIsDQ85KBonENm7/AoSH3Xl+5g=,iv:mrI11fYQbYBDH+wHjIIhqnh748c7rplaqu9obBrCI1c=,tag:+VRMTwKYEeeysPsEx5t+Tg==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:yuE/FfOBJJ1X6ztt0FYyQMZQbG1yZBJpjdSmEzel2XuJgV0gZK3AqUqIwEo=,iv:6wXNrB6rfJU/d8M+eWVTuIhZbrSS4krarvBdxEQ6uJY=,tag:eLho45EwUM8yglcgAvdAWg==,type:str]
    MONGO_URI: ENC[AES256_GCM,data:0iVz24AsKstkoqGh2u4KegzNDhADNrP2kEaT+3Cv5DJ8Asq+kzncW0gk+MwirJKg5DZ8s99DfLglNamzHtRKEg52HCym,iv:ia142MdeXVlIKyOSGDsN4JNiebwVPZDWBQNgvRz/2g8=,tag:i8MymU8oT9XY7gNh9BtTmg==,type:str]
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:ieFXT3S7AfNrGcdJuoUXiukQvpfvNydmjCZtl7PsZOm23kB1rcT+joQcWVA=,iv:TTBmXDPqnQTGLZZwRm2cpRLooqTZof5lbBa0ejQm7xI=,tag:MUUsND4XFrASMfsjNCqHBA==,type:str]
    NEXTAUTH_URL: ENC[AES256_GCM,data:aEKQy7tUSl/5ubzcUv3HNSyHinX5q6tqI9VZ2og=,iv:16P9pjoWDI4fVxMws+47Tmv2gNjXW9Z5KmZPG9xkvAc=,tag:/fHv0k/LO5bFoXgk3eWWtg==,type:str]
    NEXT_PUBLIC_API_URL: ENC[AES256_GCM,data:0uZPvqM6X9sRScp2zE/P2UTcs/um5sN5kpfwp1A=,iv:n50Yb9UDUEs6W6Wxmy/0bNkq3kXVAaxMAkTnNOYTvSk=,tag:d2uef3VxzxDfy6xxf886uw==,type:str]
    NEXT_PUBLIC_ENV: ENC[AES256_GCM,data:lKO3mu41gafVAw==,iv:TcpO1cr3VyBK6ILysXuN+CmCERykrLh0tMnZmgGVahg=,tag:XcuaY+4qwnQ4BM3RLDkalQ==,type:str]
    NODE_ENV: ENC[AES256_GCM,data:blRIVLcIstlsWw==,iv:mT/3TWUtnv9RFp7hXkhezc1uDB8rqoVmlL3EExb0O9c=,tag:om/SRroa2WvXkfJyldutaQ==,type:str]
    SESSION_SECRET: ENC[AES256_GCM,data:D/hYgOtq4mMKQ2c0/o6eQFiKfuVvM+78zFD6FyVYpQw8JX/uAU8lMpoAp00=,iv:5O8oMUGMkh0fqFGeN6FaQjIV5RfhsPchUMt7mP+6goQ=,tag:F2TNDtKKrdmNfNZKzfH9vg==,type:str]
    SMTP_FROM: ENC[AES256_GCM,data:pCVnRbgZtPxZA00c28un17ZIa7DDC1Y=,iv:xQf931faKC6VnHCa4vApTW5Nrw8w+q9xIbHIKceg64c=,tag:MJxrcYoPEscHOEkP6ex9MA==,type:str]
    SMTP_HOST: ENC[AES256_GCM,data:1G32ZPFgfzfgq4LAx7o9XfYTjQ0=,iv:TPLDLSdDbbnoxhJQ8IA6d5LQDDTCx4ABcYJv3Sltnds=,tag:N/xO0jtZDJn0EGnHAxpiLw==,type:str]
    SMTP_PASS: ENC[AES256_GCM,data:ciaEWgikFhZhuSkuFVr5qw==,iv:1ARlk7W7BjO+b6fynKkJIusaZ686g+P55LmsNBYJLv4=,tag:TT0CECSF1ivMTYagzG6PNw==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:yn6W,iv:RGGwySPs+aLg7DUyxdjOXciWpD43VhKa0PhCLRgUBwI=,tag:Iz0CratO1SCz5Aqx7Ndg+w==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:BLJNG4qvyYy1ql5CHK0cpmpbTvpLpAnt,iv:0gFXSl2MtGxHJg/NJnAURJzC355EQXsIDQfjwcN7Atc=,tag:UMzeP1ThA8lMrmD9DawQhQ==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5cHRpczlMcnRwQnBXc25z
            VTVrQ2RNSE5aa1g4VUdQK1NNQzR3dFJjYWhJCnBzb212K2MvMEZPbHZIUUxteFBu
            VGZBN2hGaEtJTlRwK1ZJNU9xNklwT2MKLS0tIDdIcXhWaE1OOTYwTE9pMXgxUk9E
            MG1Ybi8zKzA0OC96U1owMHJvQWtpb3MKcA77hDPC14MTpOh9XVwDXHnj2vWAIceK
            G5rf/hte89IXBKP0PbraMXxQsZ3491zyBI1Hg8KzUu61nAnFM1DjcA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5wsguw34gmnnllle8qzcjvjkl22e88em3a0lseqs0l9lscmr5pqsg6gyn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXOXpGemFHZktaSGRlUkk3
            S1BScWtreXJMMHFZbENaM1lKTlFGN3pyREUwCkRnWGlHdVdXeUg0b3pkd0paOFY2
            ZFRyNVZOd1djeVFqalllVGY4S1VHZXMKLS0tIHZoMGZhemdUS1BjY2NsODlYbHhY
            cjZLYUJ5RnQyQjc0OUEwVkhJejl4amMKQcOshBPbov4CfIuxM1yN52nu/DPbPi1g
            CWpUrxjV8Pf3vpcou/H2Cc6Ruc/md2Q8GzYAHwtUJoLvrEX3CMlGSw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13yvwrz6cvg8cwq78m6jvy9mndjdyuv0k3kh0du72v28puqcuafms8p28gr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-28T20:54:39Z"
    mac: ENC[AES256_GCM,data:9ZnpD4q9ZqgtZPGjrGm+DG/5k3kYeftyR0jYDqqsce5AfNJMJ3wXRE8dEnYM6NY2rAyDmP+YYLvd6/A9pkO1NIzcRxFkZ/VftrkEEOyVBWVl4EvnV7hjPiVEnOcbWrXda8MMmOMVRIbX5qlaiKxhHKRv/XAGSsB6ADdsG/5l4Ac=,iv:pGkcMP0sJlW9CfXiJZ0k8vhe+EUXJhQlpgZBz6mZbso=,tag:zeTLNec/ne/MVcqugW8aDw==,type:str]
    version: 3.13.3
