apiVersion: v1
data:
    token: ENC[AES256_GCM,data:j0leV630pbgYci593tdUUEWFlpA7BcxL32ZrrWDacFAEYwEXOG+LFJQMHS3SEmG2Mqxo1S1vX7iGWaIUKYzCmRaup8GqvU+13jUNHhC8kmwk+8/Oc8gyTQ==,iv:UFDrjnnZpIq7Mhn5108RgRQSLD9WFcJN94l/AKQ629A=,tag:AUO0ahOm7FvPr+4//GGBiQ==,type:str]
kind: Secret
metadata:
    annotations:
        argocd.argoproj.io/sync-options: Delete=false,Prune=false
    name: hcloud
    namespace: kube-system
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYcjh4aDJwbFl1VmdBSUZ4
            RnY5R3Vxc01uOE02V0RFOUtpWDkwMmI2VWtNClhQbWJMcFF2QkVQa2VWcnlhalFS
            eGpaOTZmWHl6OUZma2ptQmpCN1VTa2cKLS0tIDcwUWl0VFhPaFErVmF0R1pWYmxN
            VlNMVEJIbnZZL2JrbUhmUkgxa2x4R2MKHGogiMMJHKV27J7gHYZISKbMXSpz2Jby
            wp1V9kNugtxqAsLAr9nD1oId0e/HQqyi+kVvfewasbPSvGWLeNo89Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5wsguw34gmnnllle8qzcjvjkl22e88em3a0lseqs0l9lscmr5pqsg6gyn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqRVNrWkhlR29QOG1NY21l
            Y2ZzclBDTERITUNZNVdWbkZlL0h2M1BsVGhzCldjR05sSllwRk9wNmtrOW1BSENB
            RkhjNGh6SllEbC9KUHhqa0pzSkQyMTgKLS0tIHZGM1RrWDJYeVRiMktlRzNjdnJ2
            SG9jMnZpV2NnUkU1M3AxZmxEYUJBckUKgnC3BrsGSEqffot8jAAist8yAwOhwPei
            GFMVxSyAkwv8uII20h5gbNhauUdER3GtVJNiNMKMVjKBv/5h7kd6Vw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13yvwrz6cvg8cwq78m6jvy9mndjdyuv0k3kh0du72v28puqcuafms8p28gr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-28T20:54:08Z"
    mac: ENC[AES256_GCM,data:B5qB58NDIB4CURXI6qCVv6oLzk2fLfBwFieBcbss+ZqSOOQwjjOrXvNxLza8zYDT6WtoAN9AqiD4Eczc58ETSCWc93giJ+762SglE9KqSbhXSAXg3csS+9r+BAlxQl5f7mOk+3p7K7ZTuau/j/owsG2z/02b76aU10lgfx7zp3Y=,iv:7lomYWsuuEiwYHgApTP2t+7Ze7/HJy7CgeuHZDMHYEU=,tag:1/fdpU/miVbxdU962UsdCQ==,type:str]
    version: 3.13.3
