apiVersion: v1
kind: Secret
metadata:
    annotations:
        argocd.argoproj.io/sync-options: Delete=false,Prune=false
    name: smart-home-system-api-env
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:FabukufrarPO99Rvlk5xS8IYoJa/wrvWwGJRC2/TtlOpHvM/v5oA0/zibcbHA1DX+Ejco02CLmkUiLg72m0CVQ==,iv:yJu5qGAiGfedlc/blul+6PCBtnxkFfHQKy1pvCStGkM=,tag:lI5bYum3gS3M4vP18dnz9g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0dkhtL0UrU0JzQ01VcFVV
            LzBWOWt2R3BoVW5rV0dsRzAwQnZhM0l0YkFFCnVlVkRrc0pVWEI0S1d3U0FMeFNm
            a0xlYUloamczaTIxSnAxbWxiNWNUdlEKLS0tIEN6VDAzcGh4VkhMbTV3anJ3ckN6
            Q0hEUlplR1JVQWQvN1k3aFpOYTZaVUEKI4J+CAHvq4+oDji328jYfKJHXcSkQn/y
            CIFkDlh77rhjKXJh6dTTcllhC2T+s3RiDn4AmCtTR/wZqHhZNZ8ZGQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5wsguw34gmnnllle8qzcjvjkl22e88em3a0lseqs0l9lscmr5pqsg6gyn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpVG5yTnFJbytvSDE3THJW
            WWNjTWRqc2Jnbkw3ZVRyR2J5YXBxV1ZiMURzCllJNkhUbkxkbTV6SzNuSTZzaDZt
            UXFTSVBLVk9ITVpaV2pPUHJYdXpYNkEKLS0tIGhjc0pvOEpXcWgwc292ZE9OdUYx
            c3hsUDlDb1BIaWxzMzB1eHV1Qkp4UFUKKbwHSJXA6qiuGMhUx16XNFfaz52cM5+x
            W/hPrRuXKrzoOwrhHX8dcZhg/aIwi7Oqe4pU/ge1hTjlF2FxvE8f0g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13yvwrz6cvg8cwq78m6jvy9mndjdyuv0k3kh0du72v28puqcuafms8p28gr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-28T20:54:39Z"
    mac: ENC[AES256_GCM,data:DDAzvy02pujSTCtKg90qKg8u+6nkDkBA+/mrd7BTRgm4pjpvxCsxVetok7HlLZmJ4QNT47uUTR1EybZulKHmWMTwAVio5DvDNzASXMC/5YOZqBnaJPWF/Jp2OFsk5tS2kKjzGcl8d1WM/B7k4DqX0jipUOi1wlNRx0R+1FY8PZ0=,iv:I0qAIZpR92tyE03nUd6SFzzsHNEZXaVb7KzpMwo29Gs=,tag:8H33Y0yC6c6vN2LDyXv4Gg==,type:str]
    version: 3.13.3
