#ENC[AES256_GCM,data:UGBf2QKRa4ynt29qqJzOjxqZswJRexnOcDETnAAJ2Rynxvc+X4B/139GgY8TfEiQM/wSd9SXaQjj0MRPc+KuMoHDCuwRQn8JlHlUPYwLOXypJPc=,iv:/2IqrDM7Ye4nQgxtz0/s9Cxc5YwOL/MjGCgBw4+PCvA=,tag:8wZqTPSLPADxBA/wHP3mVA==,type:comment]
#ENC[AES256_GCM,data:vXTx7QN7wybE3dYci3D3hEXugtRIYl+LDCQbvo1vI+PMm6fCG9AeMPkxeQawIZ1XJvd/fZ0EFuVEHWHToOOeNn7siAsLFdN+h/5XBUaWLgHOBOhfWyzVvg==,iv:mzS4bmpmLYfQdQKtQm/V3dytBLFtKdoKald88/UYrc4=,tag:DPhgrIf9LaOyxwP7qyr9BQ==,type:comment]
#ENC[AES256_GCM,data:cWRQHes9oeGxsxUCctHlIDBmPZt4L4qKRX43j5w2Ad1ye6fUht+ocx+kPrkFMsv0L0HbMhNNxrcl5azAU7P8n6z5ZEgDqpfxOLndU69AHOxZuTOuAq8=,iv:WcOvmpQuhEWO9+J0SNjfrWpbq7/9AAsqmLMhmhGLyCs=,tag:lRzNVxVS0upoqBPpOB+5/A==,type:comment]
#ENC[AES256_GCM,data:TVZG75zDqKPiVHC8qrHZyfoWAuYdZBYfrznhckDetkAFA6gzTi3vSztSfaLqQDCXiFYZPLnjNEbJ,iv:ZhmhaaKDYrFuDYun03elq63CAYPzJzBE8RS+s97P1js=,tag:knK+jQsTa+wp3wwpSa14cg==,type:comment]
#ENC[AES256_GCM,data:mG09e4NwNnnf+TUSD5k1fiUGAfBHmcVz13RahtyFgwRHtE49hiMQ2yz/xu4k/srh7o+AauGbI+BYS37dQuf3WAFVOdMh8el8HPvGVdWF,iv:1Va+emUPDmA2ggQ/oL49y6hovRyfNgGi4xA+Vrpk/Rk=,tag:KD1pIxWGa9RkskpU5TuYeQ==,type:comment]
restic_password: ENC[AES256_GCM,data:/G/ZXKHe831W4+COlkds1sF5jvsi0L+SKx25i3Fa2+iH+i7pmyOVGMIhdyA=,iv:q1iM6uI1Cp8vvUp58g2UHcqvet0Oten4uCnfuSUbjd8=,tag:27ILpBk7MKIdEQV/j13Aaw==,type:str]
admin_ssh_public_key: ENC[AES256_GCM,data:9z8A/3qR5jT1w8V/+Sg3IklzECMJboDl9VrSQ+leVC6EWM4TTBYZkvz2bQ/Wh4Iuu0CWfxtNUFhd70c65vItaXr3PnKLfspVfSCRN/1PISwZQ6IV3VCgWKF1QkVKXDKYuE6CK7PGL4oYV4Q=,iv:ioCEEA39trApefblnTX/FmLpmYlYQD9wsRKdciMGjTs=,tag:UgTlRuCEgbZ5OFk2SHBI0g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmbFdzTU9jN0FTNXo3cVhp
            ZXVOS3hyQjQrOEc1d3dCUWI5dWQvUUdqbzJBCjRVdHRKRlJXNFlEYW9jeVIvQWM1
            cnk2K09YVlVOZHhjdmhCcnMyZ2g5cUUKLS0tIE1vUFNubVRKWkpzalRZVHNUUlM3
            ZllvUjVCTFRRZWFoMko1UUJxSWJXRlEK3nDZeArQ0s9HOXKHcqQ2uv+wK3wXf5wQ
            wXlCBXvJK6m4TPfkgw7Brcg70aiO7jKiWN9YKa8zSC3TDeVm7KW+Fg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5wsguw34gmnnllle8qzcjvjkl22e88em3a0lseqs0l9lscmr5pqsg6gyn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqRFhIeFhRaXNTZXpacXh2
            ZW9WalphaFBSTXlpS2FhL3F6eXBrMmkvakNZCk9uRFJDWTNtV1RuZFR0OEFjT0s5
            ZWkzdVV2UG9HaGxycHQ4TzQxM3Y5eDgKLS0tIERVVFlwenRHcUdsUDFnczYycGxM
            bThHQ3A0MzBZZ0VldldyVHA1THFscHcKrPysZAMp95pQvvYauvEH8DThBdLcsTg+
            BF9xB+OZBmHOgxjSku/lR4IZNzyRwgn4N1dcEoUrE3bqOrtZdsqUkQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13yvwrz6cvg8cwq78m6jvy9mndjdyuv0k3kh0du72v28puqcuafms8p28gr
    lastmodified: "2026-09-28T15:58:29Z"
    mac: ENC[AES256_GCM,data:ikuQ7kj13RQPVPKg3zNrrzfx5Ne5pgnvevxcc5PuyHcF85i8oqxj7m7MoVVv8+7DQtediv7jFPWr+H8SwG5dkUoPQmzIxlEwr8xCqKNcKp4+lJyEACYv1vmvQY8oZDdFuejcznkMfTn6BPYPnfwzdEJ8+1JnfPGQVIItOnelGkw=,iv:vmueAdK7BfijwUHKo9r8urH+Syi2CPESUZ8XP8u/yiU=,tag:mfXfH/9TYVuaEZZ62hMZDA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
