apiVersion: v1
kind: Secret
metadata:
    annotations:
        argocd.argoproj.io/sync-options: Delete=false,Prune=false
    name: status-page-api-env
stringData:
    FRONTEND_URL: ENC[AES256_GCM,data:lDTPpA87wJ8tfhSr2x5LgboxqGHf89/+XxHXni1F,iv:yYKLUJ1zOqzmsx4qIHMQs3QR4rMycpMk3eXaD33BhhM=,tag:Vvkk1xJAt1RJO7karBWfQQ==,type:str]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:lOFqwPB9r4DF5VkuHTZeeSvYM9l2JqcZJmM2hhCu43Sgd8120PPX4PHl/V3seTOsrELsdVVeqTQJB5rWZ1FAg47s0Gprtvfo,iv:SSZM1OGdVFfnrxArd346y6K01f70y/XlWSrAYuZS2jA=,tag:MqbSeMxR1ZAp0KSy7WL3Yg==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:T/lK33WScLHxKy/xgIrI2xRzbSSicAXpm5Mz/XnGYNUcgPs=,iv:pOvn25HKMJNE9iyi/Lr0qF+9r5G7doZmFK2ijvLYNcA=,tag:aMwrIfXiGgo2xknRrLs7cw==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:BactTPKgwy2EXXogY40XHiuy1Id6EVTooNGFMGxOo+EvZUokYYgkBnvKc9c=,iv:BaNDPu6dFk3lfnQYvJ/F0sz56RBAqvzf53pFvpiSZJ8=,tag:tArzBKnPCf4B9sFTRWQazg==,type:str]
    MONGO_URI: ENC[AES256_GCM,data:I9GuY4ttx6yuv2aOcDDd7FW3lC8pqt/lQmJI30KUby/caKO0VIJWPxyf3spCLutMtWdy4RVxcvWWN9esZVd8CtP9iGQ=,iv:kAp4zjpgA1/rKocB0BX7CDwS5fvcEdgbeUMgZorXBjU=,tag:B3G8Itjw7KF4CBg6I4Iw3Q==,type:str]
    NEXTAUTH_URL: ENC[AES256_GCM,data:E2SvRHxdK1mTllkY3o6CazbyvrcMsnn2DDYxrjFKuHQ2Sg==,iv:PoQAaFcEwyhI/OVEi5KiiXDUesnDukQfRJZLsRjQI1o=,tag:UgiHhXh2ZDRnOTBhLnU70Q==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0ekppQnp1dVQ0OGhoODh3
            dzF2VXc3SzVxdFRyWUU5S1lERnFLbzlDbFdZCjBJR0pSb3dETnN4TVppSVlTSGNY
            eHJNcUYvUXBWZUY4cm5uUE82YjB2UUkKLS0tIGEzRDlhM0RHWGJ1ZWc5VFRWeDFZ
            bmp5WWpxYXRobzcreDBRY0lITXBJcm8KR1j9X4juqcv3ZMmhnn+OYoZCHwRX3VWD
            2xXkGiJ2nMKlGXbGP42G0h8OMTax6uNThudBFCV+oZBCO1+G+g5VMg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5wsguw34gmnnllle8qzcjvjkl22e88em3a0lseqs0l9lscmr5pqsg6gyn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlbHlZRDRqY0VTUlRwR2hl
            aGl5U1NEYkZRd2hyWTFYR2pHZ2V5ZjZpQmpvCkFnTE5hdW04REhMaE1iQWx4bkh1
            aUE2bE5ra0ZqZ1c0NzJCaElhVENXZlkKLS0tIE9xeHVYbFdNMkh6cVgrMjVMRmFn
            UkpZYkxMSUlVMFEyVDdmUFRndHFyK2MKlrChoZ4oh1sl3AgPlrSpQxlL8aqR4LZo
            vuQEafTuXilP0RkID9MkzyOTptDM424HR61O78PVDwVuzToCK1YSXA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13yvwrz6cvg8cwq78m6jvy9mndjdyuv0k3kh0du72v28puqcuafms8p28gr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-28T20:54:39Z"
    mac: ENC[AES256_GCM,data:I2DvzaoFdnxFg+6OpmDgs2x/36Y+MZkhmfgt/aQMgibSfXDxqto0oLhGt2IuyeoIGnyEi1arQ9CxkOQA7XUTycAV0BRkupVAATqGcq6lt7rPTHoPvrNqVdPwP/fZ90nc6LpgewbNMi+ibhpUxri13fDZwVU3CUbonJUKVc5jPUU=,iv:dlAZdJjOh2pU0PxIjO0qmzYRG6HEV3Dc0Yslu7Ga0go=,tag:fYoz+Y9sx7l6cM1UVpBYQQ==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        argocd.argoproj.io/sync-options: Delete=false,Prune=false
    name: status-page-app-env
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:wU7bgqkD3IBTv4+mQdI+Pzn+LhNKICWP9M19xplb7f6WY6ehMfL//qM4rN4=,iv:00Ifvn0MIgstVMXBhemAggDFKU/ABxC2rHvOI86Jb5Q=,tag:O9cBUQLnsJ1lkeGQPZI7pA==,type:str]
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:cdjbuUqxjjvkaLAT2TCLIHU9QanC85dVIuEyn2/W6+kyAhAf6gV0DIZuCLU=,iv:HvGazJBxzWokoEn1BUMI8IiDBiKqGS7FAr83tmwYexA=,tag:3ojKEAS7CspusMy928EHnA==,type:str]
    NEXTAUTH_URL: ENC[AES256_GCM,data:FqUY4PyQUdskyno2yZZ2ZHdbHhgUP0ZMbzmic0/a,iv:T0jdyivkf5Bdbykxsu31hxQ2ui6L4x85PssuHcvi1AQ=,tag:ylZ/brwHdX8LV4BZPrN2qw==,type:str]
    NEXT_PUBLIC_ENV: ENC[AES256_GCM,data:YDEcWanmDRYoxg==,iv:sKHs2PBT0ELSrRUlhA947Wvj15cIet2Dr+LzszYybyU=,tag:P3ommBPXvaXabrlENSIqqQ==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0ekppQnp1dVQ0OGhoODh3
            dzF2VXc3SzVxdFRyWUU5S1lERnFLbzlDbFdZCjBJR0pSb3dETnN4TVppSVlTSGNY
            eHJNcUYvUXBWZUY4cm5uUE82YjB2UUkKLS0tIGEzRDlhM0RHWGJ1ZWc5VFRWeDFZ
            bmp5WWpxYXRobzcreDBRY0lITXBJcm8KR1j9X4juqcv3ZMmhnn+OYoZCHwRX3VWD
            2xXkGiJ2nMKlGXbGP42G0h8OMTax6uNThudBFCV+oZBCO1+G+g5VMg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5wsguw34gmnnllle8qzcjvjkl22e88em3a0lseqs0l9lscmr5pqsg6gyn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlbHlZRDRqY0VTUlRwR2hl
            aGl5U1NEYkZRd2hyWTFYR2pHZ2V5ZjZpQmpvCkFnTE5hdW04REhMaE1iQWx4bkh1
            aUE2bE5ra0ZqZ1c0NzJCaElhVENXZlkKLS0tIE9xeHVYbFdNMkh6cVgrMjVMRmFn
            UkpZYkxMSUlVMFEyVDdmUFRndHFyK2MKlrChoZ4oh1sl3AgPlrSpQxlL8aqR4LZo
            vuQEafTuXilP0RkID9MkzyOTptDM424HR61O78PVDwVuzToCK1YSXA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13yvwrz6cvg8cwq78m6jvy9mndjdyuv0k3kh0du72v28puqcuafms8p28gr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-28T20:54:39Z"
    mac: ENC[AES256_GCM,data:I2DvzaoFdnxFg+6OpmDgs2x/36Y+MZkhmfgt/aQMgibSfXDxqto0oLhGt2IuyeoIGnyEi1arQ9CxkOQA7XUTycAV0BRkupVAATqGcq6lt7rPTHoPvrNqVdPwP/fZ90nc6LpgewbNMi+ibhpUxri13fDZwVU3CUbonJUKVc5jPUU=,iv:dlAZdJjOh2pU0PxIjO0qmzYRG6HEV3Dc0Yslu7Ga0go=,tag:fYoz+Y9sx7l6cM1UVpBYQQ==,type:str]
    version: 3.13.3
