apiVersion: v1
kind: Secret
metadata:
    annotations:
        argocd.argoproj.io/sync-options: Delete=false,Prune=false
    name: mochi-env
    namespace: mochi
stringData:
    BOT_TOKEN: ENC[AES256_GCM,data:uk3uzazj/jpaxJChxAY2ulxWvfbpnUSxiErzIpDMI5jPCaXuVyL63GmDIUYoy+NUNt0TDqggIyHiEjl+ceZHuBClwwrNJZzp,iv:jCru3QGPMWZWZc/eeGnTI26+47ifvfwOFDoGRoebShw=,tag:upX1WtIxU0JnsG3Y891nMw==,type:str]
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:eeW1Pyz/YNGSNd1JHyj/swZfpMveja4Gkv1Hx9Ue88G4V+LI/nYtjET0V6gB1wsTwINCekmm5O4uk55JDOpURAjIh+n6znPfjCeaBC5sXeRxbH0K+BYttIXTeTAecW9esRsu3K73ADVV4LyZnVQLh1ucW608mpnxfQ==,iv:bTcWb2guYoHRefFXCCyO+sSs7yddjg1bpuGSUtQTG/8=,tag:JCdAvh8zaYvWMgXYqI/DVA==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQYjhhNGIraERuWWYyQ3VI
            aXNtQWxiUDdMbE13YitySFFIQ2V0eFBsVVJRCmozekVwalkzdlh1L1NzYk5MRWVD
            d1VJejFhUUQra2Z0ZzlWV0diU0Vjc0kKLS0tIHRUQUVJc3gzVFhsYUVYd1BnT3FB
            MXl3OEFMVER5ellSWko2KzBzdGZQRmcKdaORCpFic1JR+OSTn0HeJYO/QxLBT8zM
            UTGCULZ0nStvU468+Iwo7BSbyLZbOik/t4cQv8XodMbyLWA/USzvEg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5wsguw34gmnnllle8qzcjvjkl22e88em3a0lseqs0l9lscmr5pqsg6gyn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXWDhlYzFEazNEM3NMeGtt
            dldwVXBNOXJuaWh0VmtPY3haNW96bzZEV0ZvCkxvL2o3UlpGRGlUUHQrL2RlY3Bz
            b3phdGk5K2NkMlJrWkFZQjVzUWpGbncKLS0tIDJTUlZibzQyYm1MSWRrRHZTdUQ5
            YkFTMTdXajFRV2kvQm9ra1UvckRMN2sKyGf3EhRaDC3AV/UDP+p7X2mm9MRVtAwj
            Ecpq3YgZzd7446tNu4GIOD95bnbMHAy6gg0Xvnmv/Dz+ZjJdL9btZA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13yvwrz6cvg8cwq78m6jvy9mndjdyuv0k3kh0du72v28puqcuafms8p28gr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-28T20:54:39Z"
    mac: ENC[AES256_GCM,data:OUE8x7ZmpZsw1J07zzDPQwka4CjjPxzU4GXl6iOaU1YSzvrqrISTDjhz0iEZfxYYX9kFV2lu8F0YBsIzfaUj77tnE2vs0ncr/UGC8FjpCBRQysmJf2DHgww5laqrNPwxEnwUlEX5lH5/huN3QEbrrHbE3vKkHZsvOzCBrEeSBjA=,iv:Sd4ih7o/tssD8Ebl/TQh1WO0eiVvopNg1ggsiC493vM=,tag:D1+iVV+4/Yc3peJo/OF4sg==,type:str]
    version: 3.13.3
