apiVersion: v1
kind: Secret
metadata:
    annotations:
        argocd.argoproj.io/sync-options: Delete=false,Prune=false
    name: bitvault-postgres-env
    namespace: bitvault
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:+eQYgI4MnUI=,iv:gInTqU9GozQMqCex3N8sU5fr4LCZItgASLh9JW3Wn9Y=,tag:8gVKPdpiUlIuaUJgJdvf2Q==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:JDaHJtwc42jBazzPgiaau93w5l0bRJ81uv7nPnM8hqg=,iv:pBSF6d338xYMz9PCAPSxYeFcf5cYxJ4I7C/zuWIr93A=,tag:P9DGMYYCkrwWR6/jz4tebg==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:HMRMU8KwXP0=,iv:d1OxNs0T4EMKJuWwyENiDBssXms6fPj8PwHIXMBAmqI=,tag:d4GLrMr7N9vR8JBYB6vzdQ==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYVVBVMndlemRhUmR6UDBV
            RGhLMWwwcU5kRy9XRG4xdDVlMVE3cGI5QmtRCmhiQThPMGlQSzhjdThrdVRGSEFa
            SG5DdUNwS2JJU1JDb0dQL1J3NnlVMFUKLS0tIGFGNGVIUGpBeFVEWUlMVTRRWjVG
            RS9ZZUZHVFV2U0JrQlhsYVFlVi83MW8Kj2Cun3dyceI4H6n+Bow1Bgm2NDnuHnUz
            1/qpGFvbMTH08X9kVi/evBXKE/KeruS7xGRcpUkCh0p9oiJNLWJXiA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5wsguw34gmnnllle8qzcjvjkl22e88em3a0lseqs0l9lscmr5pqsg6gyn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrdjdvMGZkbXZ1Yk8vd1VN
            QWVrUVdwRS9vbm04c3RxZkZ0VGp4VDA2OGlzCnB4UHgzTm5SWXFsZEMyRHhYakxN
            SFpLeTRXVzdkdmNuV3dZU2RLQ2NBOXMKLS0tIGhzcUNtVUxZQ1dFdDR1TDIvZVAw
            Ti9XVXRGRm81alJTem1hL1VrY3BIRVUKWKtO4olNB2bsm+q439azErEll5uYC4cu
            ADRm6bJ8U2JRTAUtdnwbxwzZlXYg7lqwaBoGC9lGo9h5PIsTXbnvQw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13yvwrz6cvg8cwq78m6jvy9mndjdyuv0k3kh0du72v28puqcuafms8p28gr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-28T20:54:39Z"
    mac: ENC[AES256_GCM,data:R0O0Ajyb9EcPKKBmIdNOQAZL3vFGU61UkiISa652nUjhZ1VrMcTn8zzo7O95P8UBEu4rzzC9KwEVVDXtvZ989g8JqU5Rj8zpkRQPijsJGhG0+oU21tBCvDKJ7FGLoz68ecHroavXmPB+JakOBkyipjdtBjsal+0NLZ93Fkt58aw=,iv:9hpzSdyvs9GJuAHITXcUWWy1u4vG8KSWUAw7YbNXISo=,tag:QGlK01MWCFibZ2/aauKYXg==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        argocd.argoproj.io/sync-options: Delete=false,Prune=false
    name: bitvault-minio-env
    namespace: bitvault
stringData:
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:/5b6XDo926qKbVXHBRugokM2nxYIkSKZylRJ372F40k=,iv:Ic4ZziETt0SYoUjUu3vOqieCWctHCaQwdlLbODht1Jc=,tag:i8c4rXV8/5emE9jYxpry6Q==,type:str]
    MINIO_ROOT_USER: ENC[AES256_GCM,data:3AInLFsTcVxstV6jQ0Pzsz8iAEo=,iv:7mEM9wessae+tndCRwyvczdylMMLLsWzrXE/cg1R4Mw=,tag:nS7I+51Gq0eo6wo9wNpuNw==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYVVBVMndlemRhUmR6UDBV
            RGhLMWwwcU5kRy9XRG4xdDVlMVE3cGI5QmtRCmhiQThPMGlQSzhjdThrdVRGSEFa
            SG5DdUNwS2JJU1JDb0dQL1J3NnlVMFUKLS0tIGFGNGVIUGpBeFVEWUlMVTRRWjVG
            RS9ZZUZHVFV2U0JrQlhsYVFlVi83MW8Kj2Cun3dyceI4H6n+Bow1Bgm2NDnuHnUz
            1/qpGFvbMTH08X9kVi/evBXKE/KeruS7xGRcpUkCh0p9oiJNLWJXiA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5wsguw34gmnnllle8qzcjvjkl22e88em3a0lseqs0l9lscmr5pqsg6gyn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrdjdvMGZkbXZ1Yk8vd1VN
            QWVrUVdwRS9vbm04c3RxZkZ0VGp4VDA2OGlzCnB4UHgzTm5SWXFsZEMyRHhYakxN
            SFpLeTRXVzdkdmNuV3dZU2RLQ2NBOXMKLS0tIGhzcUNtVUxZQ1dFdDR1TDIvZVAw
            Ti9XVXRGRm81alJTem1hL1VrY3BIRVUKWKtO4olNB2bsm+q439azErEll5uYC4cu
            ADRm6bJ8U2JRTAUtdnwbxwzZlXYg7lqwaBoGC9lGo9h5PIsTXbnvQw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13yvwrz6cvg8cwq78m6jvy9mndjdyuv0k3kh0du72v28puqcuafms8p28gr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-28T20:54:39Z"
    mac: ENC[AES256_GCM,data:R0O0Ajyb9EcPKKBmIdNOQAZL3vFGU61UkiISa652nUjhZ1VrMcTn8zzo7O95P8UBEu4rzzC9KwEVVDXtvZ989g8JqU5Rj8zpkRQPijsJGhG0+oU21tBCvDKJ7FGLoz68ecHroavXmPB+JakOBkyipjdtBjsal+0NLZ93Fkt58aw=,iv:9hpzSdyvs9GJuAHITXcUWWy1u4vG8KSWUAw7YbNXISo=,tag:QGlK01MWCFibZ2/aauKYXg==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        argocd.argoproj.io/sync-options: Delete=false,Prune=false
    name: bitvaultd-env
    namespace: bitvault
stringData:
    BITVAULT_DB_DSN: ENC[AES256_GCM,data:hlaFU7UnQsf1fR4Gg+Ydk3iX/nDZ68/g7TKbVke99w+eWTHoUg9mhs/J3DCjyoAGQJOzw8vttDBXoylpln+ncusnyqapN7thDLjheM4eoMtacwWZVL75wdJ43sJGQH8ce2sxzw==,iv:5KfrvxgEaOMnIlMiM8bu8287eVhLCyCehJHsxyH8+2E=,tag:49fKr9vBNhH2VNmIZhrJ3Q==,type:str]
    BITVAULT_JWT_SECRET: ENC[AES256_GCM,data:py3TmNLdif3vUN9nmInqiQFzfamBnw6K+8n1hUa6lCANSzW4YLDcSFPoFU1S4XrdCyK3GuwOW0NCsezfQ1Cvzg==,iv:KzvllzPP65bri3X2zzYIMPnZfd81jZp5uVGUUkysEiM=,tag:FaYYOHaIapFSgjiw1WBajA==,type:str]
    BITVAULT_MINIO_ACCESS_KEY: ENC[AES256_GCM,data:3Wh3njm2qsWUvtnwxK43symy0HE=,iv:wT0easRGPYCi0Q4HT18NgTyL2dj5RI1Ri1dMuUimxV0=,tag:UtHOq45uAZWA6dO8czRskw==,type:str]
    BITVAULT_MINIO_BUCKET: ENC[AES256_GCM,data:3L8ZUvigSK0=,iv:dQC2D1azyOG1h++MV+NuKWY/NzV9lQscskIcQ0uQfaw=,tag:Q8Kvo0/v6H3bH9aaFjHgSw==,type:str]
    BITVAULT_MINIO_ENDPOINT: ENC[AES256_GCM,data:3lqnUIxNJvxVcOox9OgChaAhCA==,iv:pyOSe2eKFx35x+Oh6H2oRPZIfXV4LgWWe/hsSMJJvzE=,tag:JBqvnZYzYfcmDtgkjwXkdw==,type:str]
    BITVAULT_MINIO_SECRET_KEY: ENC[AES256_GCM,data:T3TEY9hjLNNFYpw45kAfRBxMZJNiWyMprCJ6VN8WP5Y=,iv:8LG5Edx2u5PIJ5iL3dyXkr6S1RzhIts3v0Fo7l/cspI=,tag:0zdAOxQ1J1L0qftdPhVwJw==,type:str]
    BITVAULT_MINIO_USE_SSL: ENC[AES256_GCM,data:gIRWOJs=,iv:fyFM7Hw0botPsIgrjVf8BeBkC8ti6GHiXU7CqeS1dKc=,tag:996c3OpzoDEkOdb2+hDB0g==,type:str]
    BITVAULT_OBJECT_PROVIDER: ENC[AES256_GCM,data:NWq9imY=,iv:H3dZZwj5cGzsHEzXnv6YeBGFztkSonwB4hGGwM8Di90=,tag:ms/zCvUmsgUuW0eY2oua1A==,type:str]
    BITVAULT_TIER: ENC[AES256_GCM,data:zw2eeQ==,iv:WgsYX39sUIYxomnA+lqb7M5LSvoeKCMLoASCLIoEqYs=,tag:qEQH3fQ/sbR6GD5+bGiO6w==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYVVBVMndlemRhUmR6UDBV
            RGhLMWwwcU5kRy9XRG4xdDVlMVE3cGI5QmtRCmhiQThPMGlQSzhjdThrdVRGSEFa
            SG5DdUNwS2JJU1JDb0dQL1J3NnlVMFUKLS0tIGFGNGVIUGpBeFVEWUlMVTRRWjVG
            RS9ZZUZHVFV2U0JrQlhsYVFlVi83MW8Kj2Cun3dyceI4H6n+Bow1Bgm2NDnuHnUz
            1/qpGFvbMTH08X9kVi/evBXKE/KeruS7xGRcpUkCh0p9oiJNLWJXiA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5wsguw34gmnnllle8qzcjvjkl22e88em3a0lseqs0l9lscmr5pqsg6gyn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrdjdvMGZkbXZ1Yk8vd1VN
            QWVrUVdwRS9vbm04c3RxZkZ0VGp4VDA2OGlzCnB4UHgzTm5SWXFsZEMyRHhYakxN
            SFpLeTRXVzdkdmNuV3dZU2RLQ2NBOXMKLS0tIGhzcUNtVUxZQ1dFdDR1TDIvZVAw
            Ti9XVXRGRm81alJTem1hL1VrY3BIRVUKWKtO4olNB2bsm+q439azErEll5uYC4cu
            ADRm6bJ8U2JRTAUtdnwbxwzZlXYg7lqwaBoGC9lGo9h5PIsTXbnvQw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13yvwrz6cvg8cwq78m6jvy9mndjdyuv0k3kh0du72v28puqcuafms8p28gr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-28T20:54:39Z"
    mac: ENC[AES256_GCM,data:R0O0Ajyb9EcPKKBmIdNOQAZL3vFGU61UkiISa652nUjhZ1VrMcTn8zzo7O95P8UBEu4rzzC9KwEVVDXtvZ989g8JqU5Rj8zpkRQPijsJGhG0+oU21tBCvDKJ7FGLoz68ecHroavXmPB+JakOBkyipjdtBjsal+0NLZ93Fkt58aw=,iv:9hpzSdyvs9GJuAHITXcUWWy1u4vG8KSWUAw7YbNXISo=,tag:QGlK01MWCFibZ2/aauKYXg==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        argocd.argoproj.io/sync-options: Delete=false,Prune=false
    name: bitvault-ghcr-pull
    namespace: bitvault
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:I0HS72v6QgmPTF7lrDeQTG87E0hpvqmu/UUp0Pzxw51cnBWzZD6W1hibc8hfb/2WJknwb9z/yfv9XpaieUbVF53jtUCodWvB4uhiFJCM8mQn1/jF1Bym7r0EiggVP9VxipzkQSG7BhSMyb3Q0Ka1NxbQtLEcTTRdw9Msx4KaN+cZJO4V2WLXvOz6F+f7JxsOGmDW4kQ3yvPM4JHp0uvkRlCOETmaxe+5TE796bkXs0yyTWYjieAHL04kRzxyJl4E+kDs9pfqVg==,iv:16zoQGNanqzZs22YyhgCHRNzMuEueuPiX0Mfs5R1ABs=,tag:BDSoY9WPh69bheveFd4/rw==,type:str]
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYVVBVMndlemRhUmR6UDBV
            RGhLMWwwcU5kRy9XRG4xdDVlMVE3cGI5QmtRCmhiQThPMGlQSzhjdThrdVRGSEFa
            SG5DdUNwS2JJU1JDb0dQL1J3NnlVMFUKLS0tIGFGNGVIUGpBeFVEWUlMVTRRWjVG
            RS9ZZUZHVFV2U0JrQlhsYVFlVi83MW8Kj2Cun3dyceI4H6n+Bow1Bgm2NDnuHnUz
            1/qpGFvbMTH08X9kVi/evBXKE/KeruS7xGRcpUkCh0p9oiJNLWJXiA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5wsguw34gmnnllle8qzcjvjkl22e88em3a0lseqs0l9lscmr5pqsg6gyn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrdjdvMGZkbXZ1Yk8vd1VN
            QWVrUVdwRS9vbm04c3RxZkZ0VGp4VDA2OGlzCnB4UHgzTm5SWXFsZEMyRHhYakxN
            SFpLeTRXVzdkdmNuV3dZU2RLQ2NBOXMKLS0tIGhzcUNtVUxZQ1dFdDR1TDIvZVAw
            Ti9XVXRGRm81alJTem1hL1VrY3BIRVUKWKtO4olNB2bsm+q439azErEll5uYC4cu
            ADRm6bJ8U2JRTAUtdnwbxwzZlXYg7lqwaBoGC9lGo9h5PIsTXbnvQw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13yvwrz6cvg8cwq78m6jvy9mndjdyuv0k3kh0du72v28puqcuafms8p28gr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-28T20:54:39Z"
    mac: ENC[AES256_GCM,data:R0O0Ajyb9EcPKKBmIdNOQAZL3vFGU61UkiISa652nUjhZ1VrMcTn8zzo7O95P8UBEu4rzzC9KwEVVDXtvZ989g8JqU5Rj8zpkRQPijsJGhG0+oU21tBCvDKJ7FGLoz68ecHroavXmPB+JakOBkyipjdtBjsal+0NLZ93Fkt58aw=,iv:9hpzSdyvs9GJuAHITXcUWWy1u4vG8KSWUAw7YbNXISo=,tag:QGlK01MWCFibZ2/aauKYXg==,type:str]
    version: 3.13.3
