apiVersion: v1
kind: Secret
metadata:
    annotations:
        argocd.argoproj.io/sync-options: Delete=false,Prune=false
    name: ghcr-creds
    namespace: argocd
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:Oh4AgpkSv93tHMrPt33lt6aMGSr87j+yCjNcrsJLFbklAixMbXMOjvJkRajOJFBGxi2S8QJz5uvUzUMaBqNA2ptWd1+NfYcvJxLGcTzmijqRM0+fN8Dv89LMRqnocpF3KOzcwZKPUbo5zM1MWTQmDq1b8e0jxZruIF/H8Q1C/PEomBs2UKK6Oj71tAtwIe5UtanEPtLkmX6eIMuBz8Q6GKlbC9fcZTO3TcMmC5guCaeZA3HGLhdfg5KgbBt3JDr2K5E1pMW2tA==,iv:vg7CF/3ACUuNIuDrNCrR50kHqhuY9GtzwH5WP/pfHmI=,tag:SOrHihFDISjrd6HVgWU4XQ==,type:str]
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWOHZldUNzYXRKUXlMdFpp
            R1RvTUQzSThSNjNnVm9YSXNnUGFoa0wwUDFzCk5xOWo4RnNVK0hjZy9ZanYwTjNx
            L05GLzRobXZ5dWdDSVpyQk9yQjlvRkEKLS0tIHUrYXZWQWxpYkdhMHNSUjFEOTBC
            cWlubE9HYVdqY21iYWo4QklFVXpZMW8K1YTZsL4IuK3BZ/1+1Vb5NQgnc0S/ZOFk
            cd8SPedOrvOoa6tjK9PNbB8bCI5wIDdC1fL9onzPaBnMPZ8Uk7Q0rw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5wsguw34gmnnllle8qzcjvjkl22e88em3a0lseqs0l9lscmr5pqsg6gyn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLRDc4d0FXdi80MkNEY095
            VWpacXUzOHhUdDhBZzV3YW1od3cxQXpoaHg0CjVoQ2JrUWY4VEE5RHNyU0V0TGFr
            TmVrZWVKVHZXa09kN3QvMjJ2WEptNm8KLS0tIERkeEZrVVpPeTEwTE1iZ1ovNmtk
            VDZ1aTZpUjdpMlBtL0cwVlQvYy9nNFkKKZsx4YcYs+GbrrwXdDhOJx+8NbKrpAtw
            4Jh3mw8LPvvgQRPVHWnLf78WReATjMgo65PnNO2ZthM4JRPiMvuBuA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13yvwrz6cvg8cwq78m6jvy9mndjdyuv0k3kh0du72v28puqcuafms8p28gr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-28T20:54:40Z"
    mac: ENC[AES256_GCM,data:85MuEFmjhKMnOfHRjGwi2r+lwY8NJ7DHXwLA2Gd/ElrHY6gq9StJH+cchOeyQXWc+ZJMXomErGJ+YNvliWo3QX6+mgKoKgPuhvJ94SXugMfe5IehkVrraMmemvASS3ZtgzJqPHtn80bNd6JsP/w5NwmHJS6mnluZhyhUVhylO3s=,iv:AagXa2wf4lA59WVI+3ut+75+gH6GTOZJvGygl6hZQ/4=,tag:wFrjruaSTBcwL2CtuxDSAg==,type:str]
    version: 3.13.3
