apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: upayan-v5-app
  namespace: upayan-v5
spec:
  hosts:
    - upayan-v5.upayan.dev
  scaleTargetRef:
    name: upayan-v5-app
    service: upayan-v5-app
    port: 3000
  replicas:
    min: 0
    max: 1
  scaledownPeriod: 300
