apiVersion: v1
kind: Secret
metadata:
    annotations:
        argocd.argoproj.io/sync-options: Delete=false,Prune=false
    name: upayan-v5-api-secrets
    namespace: upayan-v5
stringData:
    DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:Ajv8JLRZx2B45Sv6Fywt03ekbhHbPh3byE2V6svYpj9y2JtVtgOu/4IA0IJ0UzrciXRHHpRzhSK2EninNSypSSeq3SLNFLkE,iv:7XHjatUYmnl9fl8F1RObfUV7fORYM29tqi+qtcnOhVw=,tag:KKv+hLJl7lhhnk/a1gHPiA==,type:str]
    DISCORD_CLIENT_ID: ENC[AES256_GCM,data:uR9FfPRf9JyMjr/qUNMWkGt2xQ==,iv:kML8WolsVrhdEIUC+I8Y5fpLUm9IUF2qRH9qUci9d34=,tag:HoCOZ7sjwwZOPAPjteaugQ==,type:str]
    DISCORD_CLIENT_SECRET: ENC[AES256_GCM,data:KlsfQk+0FZAFikTOnCXWhJJzjUo0ZIVsZevPz/QMddQ=,iv:82fXl0jpaLmJzpQ4Ekwp+LTXSCn43dbNVkT3rZR3jig=,tag:MPoKZafnaMUt6jYlsqGmuA==,type:str]
    DISCORD_USER_ID: ENC[AES256_GCM,data:l7TQDi0qRGn9/zuoSW4IDpKT3g==,iv:Yz6BPF+rsoE3+HsE4JcKZ7rJGZfKa16Nuf7Ud1NND9E=,tag:s0HOVYnrL0y4PhrWVfaMkA==,type:str]
    PORT: ENC[AES256_GCM,data:PqqIwQ==,iv:kJ9Kk4PwNhLFxBTy6xA0O8SrTBkYqWxhtkA89I82fGQ=,tag:S+IJAVplSef+mWCMaQvidA==,type:str]
    SIGNING_KEY: ENC[AES256_GCM,data:4pzICHeZsPIvJT7QfsySEyJVrR8HnM8kYRrmqR8pBXkK1z78Kn1VZEFNOQ==,iv:zx3+lL7tsTUrxntX0Fg4M4kqC+4DdNiU7Bpu4LSkPro=,tag:z3qXpm4VSRrp4AFOIUxF0g==,type:str]
    SPOTIFY_CLIENT_ID: ENC[AES256_GCM,data:vqnNIzKOhQBpwOgRXkpJeJomOjXYpv4rW+4EMIlgfBA=,iv:hTS1zJf6qBs5bJbJD5ZzQtoy9EkU+3UyIuLkcn3osyY=,tag:Sb05WOGXnjSilzZroaLl/w==,type:str]
    SPOTIFY_CLIENT_SECRET: ENC[AES256_GCM,data:zbSt6VXDqi0LKGclFXIDeUHLtp6JPLChRPXBqVW/Ipo=,iv:BFbnFI2AVlbi19l8DYQtcauxm1XcofN12ic0o6klUL4=,tag:1hzvoHUw1i/pcXObP8z1yw==,type:str]
    SPOTIFY_REFRESH_TOKEN: ENC[AES256_GCM,data:os8SOUMPzSbbh5oM+Nb8ThUcWC9X2vY0E+lj5dMfOxz3bGeFRNZTuD5OGvNwiB4yO/bRzvk3EpY2UTl3Gjq7snHyfGGQAys23BELUfSnT4KOmOOAxwgiBwHEy8NdLRc7FTkc+TJ5TzU1MGAtlMYQSG9h4cWcsm5MBjVfKc9/JoGQvZM=,iv:2k3DQPpHd0Iepto2mJHlal7RYXxt3E1MglJszye15Mk=,tag:bvgxsoTDWt901yiJJG2kBw==,type:str]
    WAKATIME_API_KEY: ENC[AES256_GCM,data:RregSvLGy4R/oFqkxjzcvMk2uf3Iv6ZAtljhpyfCG8NoRzRt7hJ2fPQ=,iv:KVy45I2eEjNqHeD0b9xiaf9Sj58Ivx+B2wKiwFWCBSo=,tag:9YhrX0k3KYskxwD4J9fbAw==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLMy9kWXNTcHBmSGo3UVZV
            a1RTY2R6NE5ETExuSG9jSkQva1ZCZkJaR1VVCm5neTlMSjBJZGxtMEJlbXBYMklQ
            Y25YZUhLOUQzUDlBRWxQNU9ERC91ZlUKLS0tIHJ0RjVZeit2TzhKa2k4cGhVa1Zl
            WlRxekdWajlidkNKNzhvSkFtTmVGRHMKQLvYvxchoVWZznVgJPtANhFE9X5a+oO8
            9nwjqCvKoSYCOgZHZbF9cFPczSzfHRPbP7fd6YhtOeP2hpI2JgopQg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5wsguw34gmnnllle8qzcjvjkl22e88em3a0lseqs0l9lscmr5pqsg6gyn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVbUVkRGpHekpCOS8zQTBS
            Sk5mSzdnZkpDb25GN2lyRTFaNm1VNThLUERNCmJDYWZhV2xGSWtxVWJaKzQ1K01L
            cU9sZU9lajN5REluS2pHSEhMQnpxd1EKLS0tIGtxaHRPMmdMM29tSjU5U0VYSGlv
            dG8vbzlSU2JHa3UwZCtQQnk5WndxeXcKqGwhxoOCtMdSanoxIt2t1rqPbb+wpeMr
            UmhESPJ/LXYOaw7nEIoEPYHCC/QknwUp5gitbhZG/n8UoEvFDe+HKg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13yvwrz6cvg8cwq78m6jvy9mndjdyuv0k3kh0du72v28puqcuafms8p28gr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-28T20:54:39Z"
    mac: ENC[AES256_GCM,data:zHVkMBslVTKyEEUDLq3movsFPEeJY/de8CC/ba7Hg1TR1WjvJ9kdqYDCLUUT5J3IhF3GpoUOCnROjxJjLbcFbUPlaj5N26cIyuisVFaAjtbvQ1PauR6zBIVxOedYcWCL3f6nR+fqCEINHLJ0SkUQtcYACZ7xbLRGyEeky1R7kCM=,iv:jeeYpKSQx+dbXhPUtAjLqL7ERm4K2GnkJ/QWobIsKkY=,tag:XXzxexrZE5zMDztK3SX7Fw==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        argocd.argoproj.io/sync-options: Delete=false,Prune=false
    name: upayan-v5-app-secrets
    namespace: upayan-v5
stringData:
    NEXTAUTH_URL: ENC[AES256_GCM,data:isEYYvD+ZIgzZvwoI6XgVdbbFCKvy608jmnQHCnAyVI=,iv:8aV/Jf07p3SWxMLL6r0SksQmfURF7BJ7LYog1nmVAgU=,tag:qJbRhfPZ3JEyfi/51NbfSg==,type:str]
    NEXT_PUBLIC_AI_URL: ENC[AES256_GCM,data:EvpErEeY1CbYwG0WyK+1yjg+BnaP7DhaGl4BxHKqlw==,iv:OxONmH85FwOZph4qLMKvbg1Gut/IcZH5MExeo+iz3jw=,tag:coKvpuHPXGkZpEu9warOrQ==,type:str]
    NEXT_PUBLIC_API_URL: ENC[AES256_GCM,data:vV3FLbz2sQ3FJYSt0jrs2ltg3KeNEB/JwqxXO0shPcw=,iv:S1HxLAtlqZkfxnywhmfhKmI4yHGJbRDdtHEhnfSoXIU=,tag:ehfi0NbuucpxymSZVGe28Q==,type:str]
    NEXT_PUBLIC_ENV: ENC[AES256_GCM,data:bPOYlaVJlTj+eA==,iv:DDxzp2KB4i2c+PxknltcCs/dk/bw8/l79i5+nV4+O08=,tag:tzJA8Eh3Nilt0tX35HrBkg==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLMy9kWXNTcHBmSGo3UVZV
            a1RTY2R6NE5ETExuSG9jSkQva1ZCZkJaR1VVCm5neTlMSjBJZGxtMEJlbXBYMklQ
            Y25YZUhLOUQzUDlBRWxQNU9ERC91ZlUKLS0tIHJ0RjVZeit2TzhKa2k4cGhVa1Zl
            WlRxekdWajlidkNKNzhvSkFtTmVGRHMKQLvYvxchoVWZznVgJPtANhFE9X5a+oO8
            9nwjqCvKoSYCOgZHZbF9cFPczSzfHRPbP7fd6YhtOeP2hpI2JgopQg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5wsguw34gmnnllle8qzcjvjkl22e88em3a0lseqs0l9lscmr5pqsg6gyn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVbUVkRGpHekpCOS8zQTBS
            Sk5mSzdnZkpDb25GN2lyRTFaNm1VNThLUERNCmJDYWZhV2xGSWtxVWJaKzQ1K01L
            cU9sZU9lajN5REluS2pHSEhMQnpxd1EKLS0tIGtxaHRPMmdMM29tSjU5U0VYSGlv
            dG8vbzlSU2JHa3UwZCtQQnk5WndxeXcKqGwhxoOCtMdSanoxIt2t1rqPbb+wpeMr
            UmhESPJ/LXYOaw7nEIoEPYHCC/QknwUp5gitbhZG/n8UoEvFDe+HKg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13yvwrz6cvg8cwq78m6jvy9mndjdyuv0k3kh0du72v28puqcuafms8p28gr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-28T20:54:39Z"
    mac: ENC[AES256_GCM,data:zHVkMBslVTKyEEUDLq3movsFPEeJY/de8CC/ba7Hg1TR1WjvJ9kdqYDCLUUT5J3IhF3GpoUOCnROjxJjLbcFbUPlaj5N26cIyuisVFaAjtbvQ1PauR6zBIVxOedYcWCL3f6nR+fqCEINHLJ0SkUQtcYACZ7xbLRGyEeky1R7kCM=,iv:jeeYpKSQx+dbXhPUtAjLqL7ERm4K2GnkJ/QWobIsKkY=,tag:XXzxexrZE5zMDztK3SX7Fw==,type:str]
    version: 3.13.3
