apiVersion: v1
kind: Secret
metadata:
    annotations:
        argocd.argoproj.io/sync-options: Delete=false,Prune=false
    name: backend-env
    namespace: vcap-staging
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:yTGRpLwMVjPnJJAH8dgVLg2SMQkNeIXX/qvoprXCGrWFXEqxTwe8K1ALgmI8g2JCUobW/22sGoQ/YJBdOrJ0NUuky+siJ0oHn9/crvop4WMxhnDWCw+YGtkznHxdwJw5EDzBF7asgw==,iv:7nSrwPf6xdNXJCymALEFgJOajxWr6/CqWbJFKizeOXE=,tag:3aSq3Gd9G/PKSOY6eVUd4A==,type:str]
    DATABASE_URL_SYNC: ENC[AES256_GCM,data:rMgfSRu43nEB6Rl/9hq6rS5S4GqZ3Cu+/e1A0BlVCX9cEYSfOjXc6msB+C15Lp3SLy8NVRwnDdezLt3cnOU8zKuAQF115F5qrH6IujRCHUiyQVhxnFb8bzSQSQqZpPN27ihbW86fOg==,iv:hb7h34pHyl1Cyb9v80h0HCRMghjV6mtsGWJ+j2E4Fgo=,tag:owllqg2awCGI3SspCX/VBQ==,type:str]
    INTERNAL_AUTH_SECRET: ENC[AES256_GCM,data:/k9DBriRcVEfbRiVKe1VnI95033v/Nh2LyJjybewGlDBBUMk3O1AeGaDxGs8x9+vEmmQ/mlw56Jy/5kG3Xnohg==,iv:lNLiK56oSHdNPG+3M0qlGvlHjKIUY6dDaLSp1rYsr4Y=,tag:UHyhrA5qliUEunkagHEEGQ==,type:str]
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:+GG2usRyt38yNg==,iv:eJcA2ByrWcvY8h0f7oS1SvQ15lyuEaUgkwmN5lgF01o=,tag:wpWAtaalhBBXRYyGZ0eGiQ==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:GGcV0Bm1B9g9jw==,iv:20dep5NaVxgqyv86EH7IZbzvfGA6kxxhQ619ufrZB7s=,tag:ZKi5PX1Ezg36nYTiQiIEkA==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:XhtsfA==,iv:tLHTpdrkRbge54GOQIPj5fT3S0Ax10yt/NojactjshU=,tag:KqIi1xo+7GwM/ktboXD5QQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:dIWjSw9xYYDX30e9rmY7JQLU/H4Dz4YhEDu71gwiozg=,iv:ae8gIS9wFZPr3HL7ZPvHjG8XvhcolI0Za9mZ09IEnmE=,tag:K/Aa792B24IXN59GJxYVKA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:NV1XGx899dQl,iv:sMTDgyiMzydrCKKW9NKhb1/gUENFKlbZ/n0yBKcKiNU=,tag:liAFGiBQe7ITeW3KwfE7hQ==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:YQO4MvNj/+oE10Zu9YYY5p3gsAWMnmo+V5z7TTy/9zcye9gcHiKCPvc=,iv:JUysB0h7UqxbMI94okgLznGiu5K4JGr9XqqAj74hYKY=,tag:U8Ij2QQ63ugIYBdo14hOAQ==,type:str]
    SIGNING_CERT_PASSWORD: ""
    SMTP_APP_PASSWORD: ENC[AES256_GCM,data:h15VXI2wLf8x0yZyAZg4RRa1Ww==,iv:8ScQF/XpBVAaH/EjFM9/iOGasxQ+LK/ZCqm5MBGgw2o=,tag:CEKRzxDkgEpzg0WlG6vaXA==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:D73uXJrJCAnTJpik0cgiIS3c,iv:hDJrpYUtg+rccSc82FpMrX1107qc4XKa2plb8L7/TpI=,tag:/dNizS5w9NsLXbD7IigJMw==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBURGlpNEt6QWVQcXZpejBa
            OUo3ZEhyVTZuaXNidUlsQURyTVBPL3BGYkJjCktOMFE5TWNEZk1hdEp3aC9vbVBL
            NUppTTZFbWJNM0JBRzRMNWFGNkVSa2MKLS0tIGJQUnpQNHo3Y0lrOVh1UTRZOUlT
            RG1wTTFpSTIwTE41NEZ5M0FmWjhJM28KGkSvBfmF3SBysdwXjxkkAFZ4Fdw4BiTf
            Ghsth6uavb9gUx0BRkEYyN0pgAUFaVNl5EXi8q1rdeLzMi2FIpEFsQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5wsguw34gmnnllle8qzcjvjkl22e88em3a0lseqs0l9lscmr5pqsg6gyn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6OEFaUyszZTdVblBoVzMw
            c2RkTzZLc3JFUnpsVnhSNmk1MFZ3MlR4dndzCnpTdXlxWUNGaDJpTHJoSXlVK2Jq
            WXQrMG5JTksyL3RjZzNVOE81WEhhVTQKLS0tIDE5Vk5MT0c0NUxUNDl1OWhoREVs
            bU1Uc2ZtaGNqV3BCVEx4NWNnMVoyL00KZdEj8XfsFfyQXOgz1kB+TgYoF7eqiefF
            H65LDrJTThbUex93q8P7NkaMs+OISK3jygvgEa0JDjvlhETFGfJ2YQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13yvwrz6cvg8cwq78m6jvy9mndjdyuv0k3kh0du72v28puqcuafms8p28gr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-28T20:40:38Z"
    mac: ENC[AES256_GCM,data:Gwi5vzO+Ajt5+2/hvX9l//gjlwGuri8MF6K3N28OxKyPhi605UimngGIvv2NGPPn++I8DxeH8YR3oO4HWHYhwBXVCo0zteBIhTIIPeHT1q/DLVXPoZE2zh0FH8jvsm1pxrEUZ/yztQRZ5jztcG/p7StFk0ysS8Iq/uP/Rzsv+QU=,iv:daH8GhBYYWHP4kwe+smwnCjFq8TOF1roFoY2d9kiQyE=,tag:irVvwbzzBpgbJvis4DLniA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        argocd.argoproj.io/sync-options: Delete=false,Prune=false
    name: auth-env
    namespace: vcap-staging
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:jwWfLyc+AoPGdRrXtqIE6JDUur0cMC8NcJ7OmFyriLEvnkhtfj39UNZUrLyUP3kdoSFxspGFlFriiqwK/cyjhpUYhst64q3hs0h86bIWlRS5r56jtLARBw5ySqjf3NmYPKGFsjgOJw==,iv:xObav1yzAxK8u1lzhNPcrHSZkhZoqO82lzwfCjoRfK4=,tag:RISiol3hE3kYPht2YjFZoA==,type:str]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:CKIPeT/ZX5qniCM3Q1+J+82ADlHOhWB9JOX9ipUKvrcegbHb00W3UbSDGDoSI3ht/5oz0W9RmWt1IWFQfYT//hZS+K+89MU=,iv:Z+4EyBXvDKdZ3v20xTFNHqh3UtjhXO8ZfvnovqU62IA=,tag:SvE4W8soW0r68s+Dsq/cOQ==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:eS0MsLvQiZ+NuKG14vQVD4YwuTdVbC07bydCNTh0v1BvZjU=,iv:Eb1c414mOuFpVS32dXP5O4lEmxzkDk38fQMe8FlptII=,tag:WqLNDyh9S5j49C2hZn0IXg==,type:str]
    INTERNAL_AUTH_SECRET: ENC[AES256_GCM,data:kbH4G6pq6FMSGbrtNILBo0P9M9pcXyo45wxs6Se4ky1PXjnTn3yjH8GsXx3SeSsTkUcZR6rbN6Ylujlel99OFw==,iv:yubve66PaYjNxgMHY4d9WEkEaRhN/J4HThXYgq8x+Ls=,tag:/BQkB2R2wDEaR2gZZq65Xg==,type:str]
    JWT_SECRET_KEY: ENC[AES256_GCM,data:vQtvY9ipHWt+d/WMGJQrL5F7GvA7cn+Y8TnfbEq5Q944xKn4r5wrIJ1c8kHntUWUonWhhYqICBLwc0f8VTnIaQ==,iv:VTy1Uf4PwCaoAFuiHUK6LFvTdKf+WCdRzd0XJSiIUT4=,tag:EJIbGEzXqeXmSKQJFVjeDg==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:b9kGDDwJlGZuiAmbukOEd2cyyw4+tnbV1vjY+2nq3/aas7+A8tYJavU=,iv:ANWhOAYKSIGt15FlKDHtU12xaZnfg3KAtwazeggUT1Y=,tag:5VptBEXIfbv3J0mJk0KcTQ==,type:str]
    SMTP_APP_PASSWORD: ENC[AES256_GCM,data:Kdd4CL29vHPVtSV9flqZCr3B4A==,iv:y+T/51v24jjy0bWl9eM9N8vv5Mfc5w851P5R+dSZgsE=,tag:NiuYnOs8RVpR8FrBHA+SMQ==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:4Or3fXV4im/pwa/j9Jax6Fuo,iv:lFLKQZO5R3ao1bzK+bc8GGHFIgqZjXcEkACmgf0mlys=,tag:CjZNKtFlaBNXrHi/kIF3oQ==,type:str]
    TOTP_ENCRYPTION_KEY: ENC[AES256_GCM,data:AV6wUCTvmIeXVrLxNsawbB0LuhIs5zgYTAFItFJkZVn66tyd1/CwIil3szYMsxiMqLwGbFdks05FTY7dAi7tzA==,iv:IbytG+ILkETXEcg+O98/SWR+TKmmMSCzh+Y9F8OHn3c=,tag:zjswCut5DVYFcU+II4YPzQ==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBURGlpNEt6QWVQcXZpejBa
            OUo3ZEhyVTZuaXNidUlsQURyTVBPL3BGYkJjCktOMFE5TWNEZk1hdEp3aC9vbVBL
            NUppTTZFbWJNM0JBRzRMNWFGNkVSa2MKLS0tIGJQUnpQNHo3Y0lrOVh1UTRZOUlT
            RG1wTTFpSTIwTE41NEZ5M0FmWjhJM28KGkSvBfmF3SBysdwXjxkkAFZ4Fdw4BiTf
            Ghsth6uavb9gUx0BRkEYyN0pgAUFaVNl5EXi8q1rdeLzMi2FIpEFsQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5wsguw34gmnnllle8qzcjvjkl22e88em3a0lseqs0l9lscmr5pqsg6gyn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6OEFaUyszZTdVblBoVzMw
            c2RkTzZLc3JFUnpsVnhSNmk1MFZ3MlR4dndzCnpTdXlxWUNGaDJpTHJoSXlVK2Jq
            WXQrMG5JTksyL3RjZzNVOE81WEhhVTQKLS0tIDE5Vk5MT0c0NUxUNDl1OWhoREVs
            bU1Uc2ZtaGNqV3BCVEx4NWNnMVoyL00KZdEj8XfsFfyQXOgz1kB+TgYoF7eqiefF
            H65LDrJTThbUex93q8P7NkaMs+OISK3jygvgEa0JDjvlhETFGfJ2YQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13yvwrz6cvg8cwq78m6jvy9mndjdyuv0k3kh0du72v28puqcuafms8p28gr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-28T20:40:38Z"
    mac: ENC[AES256_GCM,data:Gwi5vzO+Ajt5+2/hvX9l//gjlwGuri8MF6K3N28OxKyPhi605UimngGIvv2NGPPn++I8DxeH8YR3oO4HWHYhwBXVCo0zteBIhTIIPeHT1q/DLVXPoZE2zh0FH8jvsm1pxrEUZ/yztQRZ5jztcG/p7StFk0ysS8Iq/uP/Rzsv+QU=,iv:daH8GhBYYWHP4kwe+smwnCjFq8TOF1roFoY2d9kiQyE=,tag:irVvwbzzBpgbJvis4DLniA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        argocd.argoproj.io/sync-options: Delete=false,Prune=false
    name: pull-secret
    namespace: vcap-staging
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:C7pEnWx3fQSFCWV0Nhi28H7RUk9yuZfW+oUkPYyiPKCfw8SXgPWXISz1V8TUZx5Wk4Y53w0EuiANCTzqVweuguWIba9yqlYj9dHQHI02mJGDO64QFKD014oiWdWtJYrsQ3hApAQEVoKgYVTmY+IPzP3ujbr8i9s3H02tYJcE00WmihLK2qXxlPdmpxRvocC7CtSUlBaINd7k2JYscwgMaUyrOj/NWcLPSGepGu55XcMtVW9OsWpmek/zfaILkSpBYE7MSj+X,iv:7diFnWJ5Jdl5bmR9ky/ghbcoHtaT3mS7Lqe6fVN02io=,tag:97GzSN7ToSERiMsO1FVpsw==,type:str]
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBURGlpNEt6QWVQcXZpejBa
            OUo3ZEhyVTZuaXNidUlsQURyTVBPL3BGYkJjCktOMFE5TWNEZk1hdEp3aC9vbVBL
            NUppTTZFbWJNM0JBRzRMNWFGNkVSa2MKLS0tIGJQUnpQNHo3Y0lrOVh1UTRZOUlT
            RG1wTTFpSTIwTE41NEZ5M0FmWjhJM28KGkSvBfmF3SBysdwXjxkkAFZ4Fdw4BiTf
            Ghsth6uavb9gUx0BRkEYyN0pgAUFaVNl5EXi8q1rdeLzMi2FIpEFsQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5wsguw34gmnnllle8qzcjvjkl22e88em3a0lseqs0l9lscmr5pqsg6gyn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6OEFaUyszZTdVblBoVzMw
            c2RkTzZLc3JFUnpsVnhSNmk1MFZ3MlR4dndzCnpTdXlxWUNGaDJpTHJoSXlVK2Jq
            WXQrMG5JTksyL3RjZzNVOE81WEhhVTQKLS0tIDE5Vk5MT0c0NUxUNDl1OWhoREVs
            bU1Uc2ZtaGNqV3BCVEx4NWNnMVoyL00KZdEj8XfsFfyQXOgz1kB+TgYoF7eqiefF
            H65LDrJTThbUex93q8P7NkaMs+OISK3jygvgEa0JDjvlhETFGfJ2YQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13yvwrz6cvg8cwq78m6jvy9mndjdyuv0k3kh0du72v28puqcuafms8p28gr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-28T20:40:38Z"
    mac: ENC[AES256_GCM,data:Gwi5vzO+Ajt5+2/hvX9l//gjlwGuri8MF6K3N28OxKyPhi605UimngGIvv2NGPPn++I8DxeH8YR3oO4HWHYhwBXVCo0zteBIhTIIPeHT1q/DLVXPoZE2zh0FH8jvsm1pxrEUZ/yztQRZ5jztcG/p7StFk0ysS8Iq/uP/Rzsv+QU=,iv:daH8GhBYYWHP4kwe+smwnCjFq8TOF1roFoY2d9kiQyE=,tag:irVvwbzzBpgbJvis4DLniA==,type:str]
    version: 3.13.3
