apiVersion: v1
kind: Secret
metadata:
    annotations:
        argocd.argoproj.io/sync-options: Delete=false,Prune=false
    name: backend-env
    namespace: vcap-staging
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:OXu1sf8MZlG6cYfeOKAZDW1tYsOaOwRq9Y5TU91gV5xMrIwCasqwOymsp7QyOaeJ7GP7bxEDfI2Nlhjd3/MoaxdkTI4MSu6pbTdQ74vHmPWh+h/+5yRkZ/4XXddPPJQaKm8j+I1L,iv:a10cb6Y3Q/HV+D07gmshW8Z0UidnfhuL5htAtq50GlU=,tag:4BmvY8HYk4ivs7EiiKRoFA==,type:str]
    DATABASE_URL_SYNC: ENC[AES256_GCM,data:EN4gL/PS5scdFP+OVfYZJWgxM5LgnKru4lToenV94DYkIOppkSFaWmxpUbWQ0RL6GCnZcDsc1bp4U69hNqNeFl4+EdbFh941Sb3tkdHcJS/PX7ZlWHbBKGTUhXTXbfA7UIrok8L4,iv:ouZblPUVhl4NFjkZgScxRg6uWzaxoYwMt0EZ+oNP3TA=,tag:Zro1xn8N+s4jd10sNCrf7A==,type:str]
    INTERNAL_AUTH_SECRET: ENC[AES256_GCM,data:9geccYPH6BEMM4C2wUPCe5unphbECHJxWkm4YOpEdKe9gkggK77tvbQMYj+LblTFfGBMxOuC08ljzb/n9kpkWg==,iv:3iZ8W0iPBG4agxwbTYJbwGOrQEv1aDZNFJ9E4DTuTHk=,tag:w/rodSCGQxuCZOmlexxUQA==,type:str]
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:C29W7l6XXfPJbQ==,iv:gNH5V/+7fO+3iTXbJ8gOQw2Devd/lP1VNthhkhQo2NM=,tag:K0mg6321ELGRgYVHXqQr9w==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:iTAyEnXTATrOvQ==,iv:lmj7e/uGDseV8CZzfVA6OsEQTZO/eUd+b2b7bhePUAE=,tag:CLHAUGjGxj756N9xCWleYg==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:AV2Etw==,iv:+N0J3HJ4247b088BjclRWCnQz/+XECMrKBS+GDR40q4=,tag:2D0kk2OBc6uxgtOrsV6XuQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:hIB4vXtb5bG+5+3eAaNN4mDV/iO7wSb0cpzNfaXcZjA=,iv:2er/oAi7D77+t647r+kXlv3V/rT3PK+rlpv1ysYmtBw=,tag:e4TEivao1X74z70xIXuR1A==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:N0Oz3uNYS65Y,iv:WRLDk9YwGkZRi/uT31eDiZcTtpfluZx6oMLXy1cJoOE=,tag:q8oSdDBjqQnEehg/47SS0Q==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:bt+DBchI99cHV/cO25LzAIEFKSlZWTaH+Gain743oU9o0AOQyTcXnT0=,iv:m9cgECZvSwfZNa1EiY8ECdyFAvQ52Cj2xWyc0HksneM=,tag:eG7M19khqvrOgph5LIgs8g==,type:str]
    SIGNING_CERT_PASSWORD: ""
    SMTP_APP_PASSWORD: ENC[AES256_GCM,data:eRLtFlDM1MIuovr87Ghqr3vZaw==,iv:zWKld8m2uEuk0v9YtVSlxfeItxthOwmSjTfefGUn7PU=,tag:Uj2gORO8VANUPU0Ddpu5Aw==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:4W2KaJdibmQdT6FnGrQ0XkXR,iv:f4Dom2CGlg66SNgJOABJvca1f+TO/cQNTzLwl35qdqE=,tag:w8ncRCvwujD/o7t1X6Qo/w==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBORTc5MW11RStzbTA5cmFl
            MzRSaWVPTy9Da3NmU1dLVXNQYnIvelJwb0h3ClhXbVA5elBBaHpkM2FQQWJEb0d0
            UW5sSzFvZGJndVhSUjdpUDhjNTBjckkKLS0tIDJRRzdKSTY5Qk14T1U5R3Bac1NC
            TUkybm1NOWI2akw1VWRSeVRTL25JdEUKk6cVy5FNe6Z10VCQp1Z6FRzS7pm1CEcT
            0S6lVM+/2vDj8RuYxbsxENBcv/ktH5Nre31sI/kLVrAj14sIFULa7w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5wsguw34gmnnllle8qzcjvjkl22e88em3a0lseqs0l9lscmr5pqsg6gyn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIYUQvTFZ1ZTN6VnhNODBF
            U3hwQTR2Y3NsUFRmZTFIL3hESjQ5eU5aK2lzClA1WDQ4UUYwZ3lzd3lJd2dQaUVV
            VDFhWVg0QkFQTjB4N1B6QjRmRnllcW8KLS0tIFJaVVlyc3NUckorOUlVQ3kyRUp0
            ZFJaSW0xZUhVeU9oYVVickQveTIvZWsK4btkR2QfCR1FIykr1AUVAmsRZZj+uclx
            myyU+WhBNAgAlB7Xa/8A27OeiBY+7GUBRI3xFzTzH/SagUVe7ReM+g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13yvwrz6cvg8cwq78m6jvy9mndjdyuv0k3kh0du72v28puqcuafms8p28gr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T17:46:46Z"
    mac: ENC[AES256_GCM,data:T93jzY/h0Y6bLbSO/mEr+TcHqw4AOgVK87+WnwpYXMVArrYzeBZaAqV8Rg91coSwACiP8Bl/xWrRGLY1jDUOOZiGCEJiCW7x/OHB30YS6DEi5sd5clMcT93W9XH5SN0J/15EQl1BFABymUbDnC5tCWFADf5THxFtLUcFPhFuuvI=,iv:48lAwZW8k6vxG6qaesUJul5kq03FG58vCn0WBksmKHw=,tag:xxBr1Iai0rnMT/jiGhJcig==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        argocd.argoproj.io/sync-options: Delete=false,Prune=false
    name: auth-env
    namespace: vcap-staging
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:poNBVcRypzf8SA+b4vam9sRfFtc8BYDvInCDic1yVoC1n+Li9PWu/64ySacFBz3mjKTByeuj53seXYhhpBQsappuOHiJSXDA54w/ZVUI6bnNtJ1g02eyMMprCSLp+2L8/ceIjlsd,iv:/dntuRPg8k0mQW7TmUf1ePclsxyZTGja+z5s49mqTLk=,tag:yiw2lJE5VrqDwKtN2cal4Q==,type:str]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:itkTcm7fJ+bnf2+MDxKB5UxwGESilfPfSewprFm8BHsPP19tWdUsBS863ILQpjN4c6NlJber5sgyhcKutdxpOziwysgpN48=,iv:cuPrxON+FM5ArQwf8siCdqJpK0twjiZxRaBsosPeVZ0=,tag:9BkwjBJPkjNSJVniRO6bcA==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:Rbs9doXYrDmidngLdOxLSBbKgm0T0rSH7xq3+3LHbOYTYW4=,iv:k2rE0HyG76DDM6NfRb2DZUlS5Nu1AnDZnDAM9H4n7QM=,tag:uecg5iK0YHUOmasUkMw5iw==,type:str]
    INTERNAL_AUTH_SECRET: ENC[AES256_GCM,data:0EBqt2Q8tM5jAV02+ZvrIUmcuZ4LTaWMgj0J15TmfhzRBV5y13k7eBWB/Hr9R63RcWiQoWTEVkeE/V2Br/eTVA==,iv:PIDsmtzYT/cGpSj1n2IRKK06CxZvKfZrEtb1y5prYhc=,tag:JHn0rohO6/2GW3PnTkWIlg==,type:str]
    JWT_SECRET_KEY: ENC[AES256_GCM,data:X4Zd0YM4kQiA62tTtMg0udi0/cJfVwtXMOTJzWzpPB/X1BlkryZs54UGKuqO6hQ8kOnkLZXEoP1bvIHDzkDe0g==,iv:oDTLIZFnUgfEPauqVLXp+PcQXELhhvHGRpN3dCILyfw=,tag:hV7B9GjYuQiyvwQ2GN+X0w==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:fDIHq8TVUaJwQ/S0kshEaPetxAEO8iJzRM7EZXKvr6YSh3FD5+1Rkj0=,iv:6FS2EJFuNKOkGIWBq2n478zjUUoCPaH5K84o353mY5s=,tag:bl6TMPc5K3cOphUbEMg0zQ==,type:str]
    SMTP_APP_PASSWORD: ENC[AES256_GCM,data:klvNerTdPTRYgOGzULfTsz5a3Q==,iv:o5RLAAIj5R51yHI303zFjSf1xv72wyYRoRsZwP2pKhI=,tag:aucwY84DgBD1s8RrCjmVsA==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:ec2FLYF4aWEqS2QNnyMXSm4M,iv:ON2Xe9dKLrq2qQR5X6wMML768apXTrDKkoHx92X0vUQ=,tag:FkhAnZ8TEuCpdDiFgJgyuQ==,type:str]
    TOTP_ENCRYPTION_KEY: ENC[AES256_GCM,data:matqbRSbM8CrebkGAE24LG87KTWttsN+15+RY7iQcq6XkfDHgJJxQ+uMw2CtlI09CvAXIhBBZ0bnXUOHturHFw==,iv:fDSk/Xqb7+SJscWjvfxRWu1mqUoVHuNRUXAkyTQiTao=,tag:xYG97VLNuOp10fOkQlOAJA==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBORTc5MW11RStzbTA5cmFl
            MzRSaWVPTy9Da3NmU1dLVXNQYnIvelJwb0h3ClhXbVA5elBBaHpkM2FQQWJEb0d0
            UW5sSzFvZGJndVhSUjdpUDhjNTBjckkKLS0tIDJRRzdKSTY5Qk14T1U5R3Bac1NC
            TUkybm1NOWI2akw1VWRSeVRTL25JdEUKk6cVy5FNe6Z10VCQp1Z6FRzS7pm1CEcT
            0S6lVM+/2vDj8RuYxbsxENBcv/ktH5Nre31sI/kLVrAj14sIFULa7w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5wsguw34gmnnllle8qzcjvjkl22e88em3a0lseqs0l9lscmr5pqsg6gyn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIYUQvTFZ1ZTN6VnhNODBF
            U3hwQTR2Y3NsUFRmZTFIL3hESjQ5eU5aK2lzClA1WDQ4UUYwZ3lzd3lJd2dQaUVV
            VDFhWVg0QkFQTjB4N1B6QjRmRnllcW8KLS0tIFJaVVlyc3NUckorOUlVQ3kyRUp0
            ZFJaSW0xZUhVeU9oYVVickQveTIvZWsK4btkR2QfCR1FIykr1AUVAmsRZZj+uclx
            myyU+WhBNAgAlB7Xa/8A27OeiBY+7GUBRI3xFzTzH/SagUVe7ReM+g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13yvwrz6cvg8cwq78m6jvy9mndjdyuv0k3kh0du72v28puqcuafms8p28gr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T17:46:46Z"
    mac: ENC[AES256_GCM,data:T93jzY/h0Y6bLbSO/mEr+TcHqw4AOgVK87+WnwpYXMVArrYzeBZaAqV8Rg91coSwACiP8Bl/xWrRGLY1jDUOOZiGCEJiCW7x/OHB30YS6DEi5sd5clMcT93W9XH5SN0J/15EQl1BFABymUbDnC5tCWFADf5THxFtLUcFPhFuuvI=,iv:48lAwZW8k6vxG6qaesUJul5kq03FG58vCn0WBksmKHw=,tag:xxBr1Iai0rnMT/jiGhJcig==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        argocd.argoproj.io/sync-options: Delete=false,Prune=false
    name: pull-secret
    namespace: vcap-staging
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:UMYxEUFqfinYDcwCIrUs6C7ZUBB+6G28AqwUoGi1QK2lSObuArqtv+4Csep3LapJjG8bWjiJJ2NNJRvOKYI87Ti4XRoAQ9yuP1YNRsmWzSJw+6IX5iPMHUbJvWQ58Iof5L8AGhlkfyk4C1HhfIoKoxWtpVIuar33/0K/IhTE5WeGvaTkGC3oKl+6z1boPftva7PlzK8GS2ccEBSQ9A5kcPIY+vU4s8u/m35VHkZK9ysmMVC4T9Do0LVF8CKQvGymNz81ay5H,iv:YPA7NoDkWfp+YhgdLQoxcwrCF0vfZo3/2o7ey5xs9Ac=,tag:w9XwRsfjTXKmV5KkZtyGsA==,type:str]
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBORTc5MW11RStzbTA5cmFl
            MzRSaWVPTy9Da3NmU1dLVXNQYnIvelJwb0h3ClhXbVA5elBBaHpkM2FQQWJEb0d0
            UW5sSzFvZGJndVhSUjdpUDhjNTBjckkKLS0tIDJRRzdKSTY5Qk14T1U5R3Bac1NC
            TUkybm1NOWI2akw1VWRSeVRTL25JdEUKk6cVy5FNe6Z10VCQp1Z6FRzS7pm1CEcT
            0S6lVM+/2vDj8RuYxbsxENBcv/ktH5Nre31sI/kLVrAj14sIFULa7w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5wsguw34gmnnllle8qzcjvjkl22e88em3a0lseqs0l9lscmr5pqsg6gyn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIYUQvTFZ1ZTN6VnhNODBF
            U3hwQTR2Y3NsUFRmZTFIL3hESjQ5eU5aK2lzClA1WDQ4UUYwZ3lzd3lJd2dQaUVV
            VDFhWVg0QkFQTjB4N1B6QjRmRnllcW8KLS0tIFJaVVlyc3NUckorOUlVQ3kyRUp0
            ZFJaSW0xZUhVeU9oYVVickQveTIvZWsK4btkR2QfCR1FIykr1AUVAmsRZZj+uclx
            myyU+WhBNAgAlB7Xa/8A27OeiBY+7GUBRI3xFzTzH/SagUVe7ReM+g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13yvwrz6cvg8cwq78m6jvy9mndjdyuv0k3kh0du72v28puqcuafms8p28gr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T17:46:46Z"
    mac: ENC[AES256_GCM,data:T93jzY/h0Y6bLbSO/mEr+TcHqw4AOgVK87+WnwpYXMVArrYzeBZaAqV8Rg91coSwACiP8Bl/xWrRGLY1jDUOOZiGCEJiCW7x/OHB30YS6DEi5sd5clMcT93W9XH5SN0J/15EQl1BFABymUbDnC5tCWFADf5THxFtLUcFPhFuuvI=,iv:48lAwZW8k6vxG6qaesUJul5kq03FG58vCn0WBksmKHw=,tag:xxBr1Iai0rnMT/jiGhJcig==,type:str]
    version: 3.13.3
