apiVersion: v1
data:
    admin.password: ENC[AES256_GCM,data:iZldMLJjA+k2kifr6kcsUFjzbJFdFJq0Vfun6AhQ1JqByiY/NoQoiQZLfGfgEi91w7/21eLr4Kj5jj1GPghiysBxKJh6S0H8+vx9BYr4OTk=,iv:kv2K4SeLEZYrv646Natxa1gFBYOpV++XSIdjyolrTaA=,tag:TgoXbiuGCwfZ8T357EHAaA==,type:str]
    admin.passwordMtime: ENC[AES256_GCM,data:XhukNvxoXB56HOmDqnGE54A8iYGmXpUEdX6J/Q==,iv:3bB6Bp0lnTxVpzl6KHvlBzNzzKXc+pvue1V0M+IM2Ng=,tag:5g9c/WhuIMtKGQDdDT7iig==,type:str]
    server.secretkey: ENC[AES256_GCM,data:siW7YqHs7vL2WXcKTrOSXgbOdlJWYtByhA68eD5eOdyVNo29XzDWWvl5G6v9OHmP5stBzP5jR6VKiGS1,iv:7hQQpKZMwVc1Lddo2O8dxld+XTwTLpfvC0w3MNm+ypg=,tag:3nbdp7NubXYLQvSdhebYDA==,type:str]
kind: Secret
metadata:
    annotations:
        argocd.argoproj.io/sync-options: Delete=false,Prune=false
    name: argocd-secret
    namespace: argocd
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByMWpkZ2s1Zk1NWkdDNlZr
            d1VoK0wzWFROMWQ1NmtlZUZhTlpKamtDTUJBCm1KMXcyUm91R0d5clovU3Zwd0R4
            bkZYRmhFT0kxUUNLRWdPODQzUkZTTU0KLS0tIFdBcE9HS3E2YnNOTE5xc1p6STRv
            N3Q1VEVYcUNyaEFnZHRndEhTRzZFMkEKsB1+HqQDxtbOr0TNMsJDrteFJTMMPDff
            bgCOqbYSmp/j0ujwwVz3VvpOwY0oU1an6riCiwHMlizQhQYoQyJcLw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5wsguw34gmnnllle8qzcjvjkl22e88em3a0lseqs0l9lscmr5pqsg6gyn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMdXRTWWZaS1kxMW9XOTc5
            Y0tnb1JGalp4WTc3Um1uRXRxYlU5Wi9XdUdrClFKc3JqemE3akdDWkh1cG03THJp
            clVBWHF3c2ZlYkpFNDFUQ1RQVkVTL1UKLS0tIG9FdFg5SkVXWTZzZ2hOSXlWWXFX
            Ri9HTnUxd2FNVnpscnpJZWRDNFlyMzgKwwqyMSy97+ZH0GZehFUcidmLSCqagPVL
            9jo10emgV9BFcM/NBNWNzgFv1Env6r97X9gl+tkpHEiSq6CVEC8idg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13yvwrz6cvg8cwq78m6jvy9mndjdyuv0k3kh0du72v28puqcuafms8p28gr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T14:21:58Z"
    mac: ENC[AES256_GCM,data:d4dfzhx05K3p99mPG5gtoA09oanl39M+Hu3ds0waSBIkyz7On9DRe0pJ0gmg2pBRZFA8DH22TTwa3EkBor7vM2akyCuEyVoqlDYyj/SUUSX/oEskkO3v1HNNaJf8az7az/2Dr5QZjUgYZJBQB/TVnxQHqjkrKVPHsLzEx2H2r4s=,iv:Sd5irZOmz8EAk6pvadIfweHMOPQQH8S5wrP2bSspHqQ=,tag:RbKotMgAXfVbMtJvasDTqw==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        argocd.argoproj.io/sync-options: Delete=false,Prune=false
    name: git-creds
    namespace: argocd
stringData:
    password: ENC[AES256_GCM,data:Fdwo6PsLP/90wrOIbXYdKf7/fN0EnPtZbE1oLEhXQRpqkYqHhEZbmw==,iv:oirN6+ap2aehImFR9FCsY9iXx7d42DszX9KP6hCN/m8=,tag:OSq59Jw1MKbqoKFFqsVxmA==,type:str]
    username: ENC[AES256_GCM,data:rQMMIhP2ZG29Tgxd3K4=,iv:5Mvh0SrAduJ86MBtM+UO6zhcRfMgpDgrw67EA7LQiUQ=,tag:YVNt0GxKrMxtpMGcibu2Xg==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByMWpkZ2s1Zk1NWkdDNlZr
            d1VoK0wzWFROMWQ1NmtlZUZhTlpKamtDTUJBCm1KMXcyUm91R0d5clovU3Zwd0R4
            bkZYRmhFT0kxUUNLRWdPODQzUkZTTU0KLS0tIFdBcE9HS3E2YnNOTE5xc1p6STRv
            N3Q1VEVYcUNyaEFnZHRndEhTRzZFMkEKsB1+HqQDxtbOr0TNMsJDrteFJTMMPDff
            bgCOqbYSmp/j0ujwwVz3VvpOwY0oU1an6riCiwHMlizQhQYoQyJcLw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5wsguw34gmnnllle8qzcjvjkl22e88em3a0lseqs0l9lscmr5pqsg6gyn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMdXRTWWZaS1kxMW9XOTc5
            Y0tnb1JGalp4WTc3Um1uRXRxYlU5Wi9XdUdrClFKc3JqemE3akdDWkh1cG03THJp
            clVBWHF3c2ZlYkpFNDFUQ1RQVkVTL1UKLS0tIG9FdFg5SkVXWTZzZ2hOSXlWWXFX
            Ri9HTnUxd2FNVnpscnpJZWRDNFlyMzgKwwqyMSy97+ZH0GZehFUcidmLSCqagPVL
            9jo10emgV9BFcM/NBNWNzgFv1Env6r97X9gl+tkpHEiSq6CVEC8idg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13yvwrz6cvg8cwq78m6jvy9mndjdyuv0k3kh0du72v28puqcuafms8p28gr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T14:21:58Z"
    mac: ENC[AES256_GCM,data:d4dfzhx05K3p99mPG5gtoA09oanl39M+Hu3ds0waSBIkyz7On9DRe0pJ0gmg2pBRZFA8DH22TTwa3EkBor7vM2akyCuEyVoqlDYyj/SUUSX/oEskkO3v1HNNaJf8az7az/2Dr5QZjUgYZJBQB/TVnxQHqjkrKVPHsLzEx2H2r4s=,iv:Sd5irZOmz8EAk6pvadIfweHMOPQQH8S5wrP2bSspHqQ=,tag:RbKotMgAXfVbMtJvasDTqw==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        argocd.argoproj.io/sync-options: Delete=false,Prune=false
    labels:
        argocd.argoproj.io/secret-type: repository
    name: argocd-repo-vps
    namespace: argocd
stringData:
    password: ENC[AES256_GCM,data:w9qA2s0h96jmBbkYgHg+df73/qLMbdavt07yulVvUboa3amzDqd0TA==,iv:wNQvNZWtIuvrt1YiqKyL1WZM1SeTHG6JvBM6y5AT7l0=,tag:zwe1JI5MudTIo4EKRulreQ==,type:str]
    type: ENC[AES256_GCM,data:gz1o,iv:25ANC0dL85uhiK4d4krVbh+9Myrrq/oR5jOl06dOf6o=,tag:FBAswSPMA+2uQs0raudQQw==,type:str]
    url: ENC[AES256_GCM,data:CxhuyKEoRLxs9eQL1r0oSVdwpHLzy17+wA2iEUYjMFK2wyqufA==,iv:W4W58wbgecPM5WbfYvmXKuGXZEDI68tysedyj3jqLDs=,tag:4Cv/Qldj4AdAyd6bbq4xZA==,type:str]
    username: ENC[AES256_GCM,data:nhpC/CNMU2Tj23ANp5o=,iv:vFUYGn5g0tBJ/7/fx4AyAQWQ+wVg+o5tNYEv5wRf7lw=,tag:Sk94dDzloKATHEZK5j3g6g==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByMWpkZ2s1Zk1NWkdDNlZr
            d1VoK0wzWFROMWQ1NmtlZUZhTlpKamtDTUJBCm1KMXcyUm91R0d5clovU3Zwd0R4
            bkZYRmhFT0kxUUNLRWdPODQzUkZTTU0KLS0tIFdBcE9HS3E2YnNOTE5xc1p6STRv
            N3Q1VEVYcUNyaEFnZHRndEhTRzZFMkEKsB1+HqQDxtbOr0TNMsJDrteFJTMMPDff
            bgCOqbYSmp/j0ujwwVz3VvpOwY0oU1an6riCiwHMlizQhQYoQyJcLw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5wsguw34gmnnllle8qzcjvjkl22e88em3a0lseqs0l9lscmr5pqsg6gyn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMdXRTWWZaS1kxMW9XOTc5
            Y0tnb1JGalp4WTc3Um1uRXRxYlU5Wi9XdUdrClFKc3JqemE3akdDWkh1cG03THJp
            clVBWHF3c2ZlYkpFNDFUQ1RQVkVTL1UKLS0tIG9FdFg5SkVXWTZzZ2hOSXlWWXFX
            Ri9HTnUxd2FNVnpscnpJZWRDNFlyMzgKwwqyMSy97+ZH0GZehFUcidmLSCqagPVL
            9jo10emgV9BFcM/NBNWNzgFv1Env6r97X9gl+tkpHEiSq6CVEC8idg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13yvwrz6cvg8cwq78m6jvy9mndjdyuv0k3kh0du72v28puqcuafms8p28gr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T14:21:58Z"
    mac: ENC[AES256_GCM,data:d4dfzhx05K3p99mPG5gtoA09oanl39M+Hu3ds0waSBIkyz7On9DRe0pJ0gmg2pBRZFA8DH22TTwa3EkBor7vM2akyCuEyVoqlDYyj/SUUSX/oEskkO3v1HNNaJf8az7az/2Dr5QZjUgYZJBQB/TVnxQHqjkrKVPHsLzEx2H2r4s=,iv:Sd5irZOmz8EAk6pvadIfweHMOPQQH8S5wrP2bSspHqQ=,tag:RbKotMgAXfVbMtJvasDTqw==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        argocd.argoproj.io/sync-options: Delete=false,Prune=false
    labels:
        argocd.argoproj.io/secret-type: repository
    name: repo-vcap-backend
    namespace: argocd
stringData:
    password: ENC[AES256_GCM,data:ELtiJYrsVB4M+IgQR+7RtsC0e3kEQ/MvVRTwvkzOwJGFgrvwsawuYQ==,iv:z7pCewXYpjrBuwahx8x3fVc0AYAyRbr/Wb+DEfyW+yc=,tag:zmfuts0CP8pujEhEtYJ3yQ==,type:str]
    type: ENC[AES256_GCM,data:ZaoD,iv:cpw3sw/nC6dOJmBZcx+jj+BOe8WPgIVrmSmyRXmk9wE=,tag:PAMiNBdBWyj/qr2m7ySLnw==,type:str]
    url: ENC[AES256_GCM,data:WzENeB0fLT+FqviXv461ghffsq1FVMAjniPvEQwBZfezGrW7ssHUt9cYd3mGlTlRvV22egqJmdEUOSpQ,iv:2igkqm5RSxLW6Pk7OXIuPc4E9CoyU8DwqQiF3xG26yI=,tag:lQsF/PTfeiheO340ZaN8kA==,type:str]
    username: ENC[AES256_GCM,data:wTLK9wRP3f5m+RDQE1s=,iv:YZMwurt/kuecSCFey5q31ee8V8yGDsi6ZO2tS+Z/bSQ=,tag:n1dhhPDQz0hGRdITQDzewA==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByMWpkZ2s1Zk1NWkdDNlZr
            d1VoK0wzWFROMWQ1NmtlZUZhTlpKamtDTUJBCm1KMXcyUm91R0d5clovU3Zwd0R4
            bkZYRmhFT0kxUUNLRWdPODQzUkZTTU0KLS0tIFdBcE9HS3E2YnNOTE5xc1p6STRv
            N3Q1VEVYcUNyaEFnZHRndEhTRzZFMkEKsB1+HqQDxtbOr0TNMsJDrteFJTMMPDff
            bgCOqbYSmp/j0ujwwVz3VvpOwY0oU1an6riCiwHMlizQhQYoQyJcLw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5wsguw34gmnnllle8qzcjvjkl22e88em3a0lseqs0l9lscmr5pqsg6gyn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMdXRTWWZaS1kxMW9XOTc5
            Y0tnb1JGalp4WTc3Um1uRXRxYlU5Wi9XdUdrClFKc3JqemE3akdDWkh1cG03THJp
            clVBWHF3c2ZlYkpFNDFUQ1RQVkVTL1UKLS0tIG9FdFg5SkVXWTZzZ2hOSXlWWXFX
            Ri9HTnUxd2FNVnpscnpJZWRDNFlyMzgKwwqyMSy97+ZH0GZehFUcidmLSCqagPVL
            9jo10emgV9BFcM/NBNWNzgFv1Env6r97X9gl+tkpHEiSq6CVEC8idg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13yvwrz6cvg8cwq78m6jvy9mndjdyuv0k3kh0du72v28puqcuafms8p28gr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T14:21:58Z"
    mac: ENC[AES256_GCM,data:d4dfzhx05K3p99mPG5gtoA09oanl39M+Hu3ds0waSBIkyz7On9DRe0pJ0gmg2pBRZFA8DH22TTwa3EkBor7vM2akyCuEyVoqlDYyj/SUUSX/oEskkO3v1HNNaJf8az7az/2Dr5QZjUgYZJBQB/TVnxQHqjkrKVPHsLzEx2H2r4s=,iv:Sd5irZOmz8EAk6pvadIfweHMOPQQH8S5wrP2bSspHqQ=,tag:RbKotMgAXfVbMtJvasDTqw==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        argocd.argoproj.io/sync-options: Delete=false,Prune=false
    labels:
        argocd.argoproj.io/secret-type: repository
    name: repo-vcap-frontend
    namespace: argocd
stringData:
    password: ENC[AES256_GCM,data:/4Y+XO8Vnid6vmwO0gXvtRAzfaGUZiPlm6dYDK5mU8kkIkQpqXYTNA==,iv:S7ZzZbyRGMz8Pg9uqQsvHfYckvtNvAuY/6QRl9vw5DE=,tag:YatUIP1RIE6RN62VomNSnQ==,type:str]
    type: ENC[AES256_GCM,data:A0NB,iv:8ZCVtS79Aq2DZLfSgmaERCsh74px81p6qYLjffa9+8o=,tag:4lpyFgsa6vImmIXCLAeacQ==,type:str]
    url: ENC[AES256_GCM,data:tZ6rUrpH1EP4pROnkAFj9wPSFL1+plBKZK4DFH7mQ3WiIZuKAOqgebW3JSCL/gKrY/qFEsrFv3aE3JV4Lw==,iv:h7qzYHr8LDXpuftpDxVJTGt0+ONbaTUqkVFPmOTxF18=,tag:Ou8aK17uoHTi2U4Kcsu6vw==,type:str]
    username: ENC[AES256_GCM,data:FwhIQz76XokXdaxWzxM=,iv:1UcUmYIyjOFX8Udz73UJKcEMk1UG/Ix6GcSZ95bfSa0=,tag:h18y81R21IVd03xsPYMZng==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByMWpkZ2s1Zk1NWkdDNlZr
            d1VoK0wzWFROMWQ1NmtlZUZhTlpKamtDTUJBCm1KMXcyUm91R0d5clovU3Zwd0R4
            bkZYRmhFT0kxUUNLRWdPODQzUkZTTU0KLS0tIFdBcE9HS3E2YnNOTE5xc1p6STRv
            N3Q1VEVYcUNyaEFnZHRndEhTRzZFMkEKsB1+HqQDxtbOr0TNMsJDrteFJTMMPDff
            bgCOqbYSmp/j0ujwwVz3VvpOwY0oU1an6riCiwHMlizQhQYoQyJcLw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5wsguw34gmnnllle8qzcjvjkl22e88em3a0lseqs0l9lscmr5pqsg6gyn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMdXRTWWZaS1kxMW9XOTc5
            Y0tnb1JGalp4WTc3Um1uRXRxYlU5Wi9XdUdrClFKc3JqemE3akdDWkh1cG03THJp
            clVBWHF3c2ZlYkpFNDFUQ1RQVkVTL1UKLS0tIG9FdFg5SkVXWTZzZ2hOSXlWWXFX
            Ri9HTnUxd2FNVnpscnpJZWRDNFlyMzgKwwqyMSy97+ZH0GZehFUcidmLSCqagPVL
            9jo10emgV9BFcM/NBNWNzgFv1Env6r97X9gl+tkpHEiSq6CVEC8idg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13yvwrz6cvg8cwq78m6jvy9mndjdyuv0k3kh0du72v28puqcuafms8p28gr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T14:21:58Z"
    mac: ENC[AES256_GCM,data:d4dfzhx05K3p99mPG5gtoA09oanl39M+Hu3ds0waSBIkyz7On9DRe0pJ0gmg2pBRZFA8DH22TTwa3EkBor7vM2akyCuEyVoqlDYyj/SUUSX/oEskkO3v1HNNaJf8az7az/2Dr5QZjUgYZJBQB/TVnxQHqjkrKVPHsLzEx2H2r4s=,iv:Sd5irZOmz8EAk6pvadIfweHMOPQQH8S5wrP2bSspHqQ=,tag:RbKotMgAXfVbMtJvasDTqw==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: creds-github-upayanmazumder
    namespace: argocd
    labels:
        argocd.argoproj.io/secret-type: repo-creds
    annotations:
        argocd.argoproj.io/sync-options: Delete=false,Prune=false
type: Opaque
stringData:
    type: ENC[AES256_GCM,data:LzkY,iv:FuNX9Znj/UOtSwEYW5tqKt5IaMm6D/aN1W4CM9KJzQI=,tag:n6gHd8uczAl8umrf3BL6TQ==,type:str]
    url: ENC[AES256_GCM,data:jcELUMQyeL7lIrk1+qCJi2nJQuvnRbstE9hd9pJkX8pMkw==,iv:+u5SfEJUg2l+/YgP43oTivyW1ZnGSmYNu7HvG8sl8qQ=,tag:v78VuaA/WqySaaZxSLYgPQ==,type:str]
    username: ENC[AES256_GCM,data:kAy/FAdvBooe5//8uZo=,iv:PiILgotg6+R53r/pq41e46swLCdWgBhO0abdU9yqryE=,tag:ytSKiZM/1Nh5YZGAp9GluQ==,type:str]
    password: ENC[AES256_GCM,data:5RjpP2vC6V0/65IwAhpsvviOtG7F5t1E8E6rKFI8LcOb8AAfalgG0g==,iv:OIXJ7NbQdI1K/hRyLw/NjLv6AVtX77YtGYVSxPxAzOA=,tag:qH5IHotB51Aya/d4uATV0A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByMWpkZ2s1Zk1NWkdDNlZr
            d1VoK0wzWFROMWQ1NmtlZUZhTlpKamtDTUJBCm1KMXcyUm91R0d5clovU3Zwd0R4
            bkZYRmhFT0kxUUNLRWdPODQzUkZTTU0KLS0tIFdBcE9HS3E2YnNOTE5xc1p6STRv
            N3Q1VEVYcUNyaEFnZHRndEhTRzZFMkEKsB1+HqQDxtbOr0TNMsJDrteFJTMMPDff
            bgCOqbYSmp/j0ujwwVz3VvpOwY0oU1an6riCiwHMlizQhQYoQyJcLw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5wsguw34gmnnllle8qzcjvjkl22e88em3a0lseqs0l9lscmr5pqsg6gyn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMdXRTWWZaS1kxMW9XOTc5
            Y0tnb1JGalp4WTc3Um1uRXRxYlU5Wi9XdUdrClFKc3JqemE3akdDWkh1cG03THJp
            clVBWHF3c2ZlYkpFNDFUQ1RQVkVTL1UKLS0tIG9FdFg5SkVXWTZzZ2hOSXlWWXFX
            Ri9HTnUxd2FNVnpscnpJZWRDNFlyMzgKwwqyMSy97+ZH0GZehFUcidmLSCqagPVL
            9jo10emgV9BFcM/NBNWNzgFv1Env6r97X9gl+tkpHEiSq6CVEC8idg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13yvwrz6cvg8cwq78m6jvy9mndjdyuv0k3kh0du72v28puqcuafms8p28gr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T14:21:58Z"
    mac: ENC[AES256_GCM,data:d4dfzhx05K3p99mPG5gtoA09oanl39M+Hu3ds0waSBIkyz7On9DRe0pJ0gmg2pBRZFA8DH22TTwa3EkBor7vM2akyCuEyVoqlDYyj/SUUSX/oEskkO3v1HNNaJf8az7az/2Dr5QZjUgYZJBQB/TVnxQHqjkrKVPHsLzEx2H2r4s=,iv:Sd5irZOmz8EAk6pvadIfweHMOPQQH8S5wrP2bSspHqQ=,tag:RbKotMgAXfVbMtJvasDTqw==,type:str]
    version: 3.13.3
