#!/usr/bin/env bash
# Pull the backup snapshots from the VPS onto this workstation (plan §12.9, DR-003).
#
# Why this exists: every other copy of the backups lives with the same two providers — the restic
# repository is on the host (Hetzner) and the intended offsite target is R2 (Cloudflare). The plan's
# worst-case row is "both Hetzner and Cloudflare compromised", where the only surviving copy is one
# held elsewhere. This is that copy.
#
# It is deliberately a script you run (or schedule) on a machine that is often powered on, not
# something the VPS pushes: the VPS must not need to reach into your workstation.
#
# Requirements on the machine running it: `restic`, `sops` (with the offline age key in sops'
# default location), and SSH access to the node (`ssh vps` as root — the repository is root-owned). If `restic` is
# missing: `sudo pacman -S restic` (Arch/CachyOS) or your distro's equivalent.
#
# Usage:
#   scripts/pull-backups.sh                 # copy EVERY snapshot (class-A, class-C, etcd, images)
#   VPS_BACKUP_TAGS=class-A scripts/pull-backups.sh    # restrict to one tag on purpose
#   VPS_BACKUP_LOCAL_REPO=/mnt/external/vps-restic scripts/pull-backups.sh
#
# DR-003 (2026-09-28): the default changed from `class-A` to all tags. The point of this mirror is the
# "both Hetzner and Cloudflare compromised" row of the backup plan, and a class-A-only mirror does not
# cover it — it would omit the class-C datasets, the etcd snapshots and the image tarballs.
#
# NOTE — a mirror is a second restic repository with its own key. `restic copy` needs credentials for
# both, and this script deliberately uses the same password for both (RESTIC_PASSWORD for the mirror,
# VPS_BACKUP_FROM_PASSWORD for the node). Consequence: if the repository password is ever rotated on
# the node, the mirror keeps its old key and this script stops working until the mirror is given the
# new one too:
#     restic -r "$LOCAL_REPO" key add        # add the new password
#     restic -r "$LOCAL_REPO" key remove <old-key-id>
# or simply delete the mirror and let this script recreate it. See
# docs/runbooks/rotate-secrets.md.
#
# Environment overrides: VPS_BACKUP_SSH_HOST (default `vps`), VPS_BACKUP_REMOTE_REPO
# (default `/var/backups/restic`), VPS_BACKUP_LOCAL_REPO (default `~/vps-backup-mirror`),
# VPS_BACKUP_TAGS (default `all` — see the DR-003 note above), VPS_BACKUP_FROM_PASSWORD
# (source-repo password, defaults to the same SOPS value), VPS_BACKUP_ASSUME_YES=1 (skip the init
# confirmation; required when there is no terminal, e.g. from a timer).
#
# Two things learned by running it (2026-09-28), both about timing rather than correctness:
#   - Run one at a time. Two concurrent runs against one mirror do not merely contend: each may find
#     the repository "not yet initialised" and `restic init` it, which rewrites `config` and gives the
#     repository a new ID under the other run's feet. The systemd unit will not overlap with itself;
#     do not start a second copy by hand while it runs.
#   - The first copy is slow, and the reason is the link rather than restic: measured on 2026-09-28, the
#     workstation pulls from the node at ~299 kB/s (100 MB took 180 s), so the 383 MB repository took
#     21 minutes. Later runs copy only new packs: the next one took **25 seconds**. That asymmetry is why
#     the first run belongs on a timer rather than in a terminal.
#   - Do not edit this file while a run is in flight. A shell reads a script as it executes it, so if the
#     file grows the running shell resumes at the wrong byte offset. That is what happened on 2026-09-28:
#     the first run copied all 383 MB and then died with exit 127 on a fragment of the comment block that
#     was being edited, so the unit reported failure although the copy had succeeded and the mirror was
#     intact. Edit, then run.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SSH_HOST="${VPS_BACKUP_SSH_HOST:-vps}"
REMOTE_REPO="${VPS_BACKUP_REMOTE_REPO:-/var/backups/restic}"
LOCAL_REPO="${VPS_BACKUP_LOCAL_REPO:-$HOME/vps-backup-mirror}"
TAGS="${VPS_BACKUP_TAGS:-all}"
SECRETS_FILE="$REPO_DIR/ansible/group_vars/vps/secrets.sops.yaml"

require() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "ERROR: '$1' is not installed." >&2
    [ "$1" = restic ] && echo "  Install it (Arch/CachyOS: sudo pacman -S restic) and re-run." >&2
    [ "$1" = sops ] && echo "  Install sops, and make sure the offline age key is in its default location (or set SOPS_AGE_KEY_FILE)." >&2
    exit 1
  }
}
require restic; require sops; require ssh

# The restic password is read from the SOPS-encrypted Ansible vars on each run, using the age key on
# this machine. It is never written to disk and never stored alongside the mirror.
if [ -n "${RESTIC_PASSWORD:-}" ]; then
  echo "using RESTIC_PASSWORD from the environment"
elif [ -f "$SECRETS_FILE" ]; then
  RESTIC_PASSWORD="$(sops -d --extract '["restic_password"]' "$SECRETS_FILE")"
  export RESTIC_PASSWORD
else
  echo "ERROR: no RESTIC_PASSWORD set and $SECRETS_FILE not found — run from inside the repo." >&2
  exit 1
fi
[ -n "${RESTIC_PASSWORD:-}" ] || { echo "ERROR: could not read restic_password from SOPS." >&2; exit 1; }

SOURCE="sftp:$SSH_HOST:$REMOTE_REPO"

# `restic copy` authenticates against BOTH repositories. The source on the node was initialised with
# the same password as everything else in /etc/vps-backup/env, so reuse it — but allow an override in
# case the two ever diverge. (Omitting this is not an obvious failure: dest-side commands work fine
# and only `copy` dies with "an empty password is not allowed".)
export RESTIC_FROM_PASSWORD="${VPS_BACKUP_FROM_PASSWORD:-$RESTIC_PASSWORD}"

if ! ssh -n -o BatchMode=yes -o ConnectTimeout=10 "$SSH_HOST" "test -d $REMOTE_REPO" 2>/dev/null; then
  echo "ERROR: cannot see $REMOTE_REPO on $SSH_HOST (is Tailscale up / is the alias right?)." >&2
  exit 1
fi

if [ ! -f "$LOCAL_REPO/config" ]; then
  echo "Local mirror $LOCAL_REPO does not exist yet."
  if [ -d "$LOCAL_REPO" ] && [ -n "$(ls -A "$LOCAL_REPO" 2>/dev/null || true)" ]; then
    echo "REFUSING: that path exists and is not empty. restic init would overwrite it — move it aside." >&2
    exit 1
  fi
  if [ "${VPS_BACKUP_ASSUME_YES:-}" = "1" ]; then
    echo "initialising (VPS_BACKUP_ASSUME_YES=1)"
  elif [ -t 0 ]; then
    read -r -p "Initialise a restic repository at $LOCAL_REPO? [y/N] " answer
    [ "$answer" = "y" ] || { echo "aborted"; exit 1; }
  else
    echo "ERROR: stdin is not a terminal and VPS_BACKUP_ASSUME_YES is not set." >&2
    echo "       Re-run interactively, or with VPS_BACKUP_ASSUME_YES=1 when you mean it." >&2
    exit 1
  fi
  restic -r "$LOCAL_REPO" init
fi

echo "== copying snapshots tagged '$TAGS'"
echo "   from $SOURCE"
echo "   to   $LOCAL_REPO"
# `copy` re-encrypts for the destination key, so this reads and writes the whole snapshot set the
# first time and only the new ones afterwards.
#
# DR-003: the default is now ALL tags, not just `class-A`. A mirror that holds only the class-A
# snapshots is not the copy that "survives losing both Hetzner and Cloudflare" — it would silently omit
# the class-C datasets, the etcd snapshots and the image tarballs, which is most of what a rebuild
# actually needs. `restic copy` without `--tag` copies everything; set VPS_BACKUP_TAGS to restrict it
# deliberately (e.g. for a fast partial refresh), never by accident.
if [ "$TAGS" = "all" ]; then
  restic -r "$LOCAL_REPO" copy --from-repo "$SOURCE"
else
  restic -r "$LOCAL_REPO" copy --from-repo "$SOURCE" --tag "$TAGS"
fi

echo "== verifying the mirror"
restic -r "$LOCAL_REPO" check
echo "== contents"
restic -r "$LOCAL_REPO" snapshots --compact

echo
echo "Mirror updated. This copy is the one that survives losing both Hetzner and Cloudflare;"
echo "keep it somewhere that is not the same disk as your working tree if you care about that case."
