apiVersion: v1
kind: Secret
metadata:
    annotations:
        argocd.argoproj.io/sync-options: Delete=false,Prune=false
    name: backend-env
    namespace: vcap-dev
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:Ze6bkTjp92MrJsIFHEfIZFNrP9RlhUmVBuShcViahxuxRzZr0AYSgTRA4td31OSFFF93SrcnYNus2vaLSYlDVKM573MTY19RTh6oANVFCXeDIqbgjcZHw6Gm+UYrT2VTnNMS,iv:G+r96EHKfnpKgG0lBZ2QqlRvGwCz5A8MFUdk0AIbp/M=,tag:clOyKQ+nQgcGXSm5rkY7GA==,type:str]
    DATABASE_URL_SYNC: ENC[AES256_GCM,data:zbIeTc/xCysxQWC8ABWZHwT9FmLwTJSG9/RlX6mn7mRo6geJLlPROa1yj1GeeMYHNEv8g0W4zbelW4Fhrlp/00oEy/x5sGfLnFW3JC+DZ7/y6FmEjRzN8CuS6Pmnla22Ldbs,iv:lD/NmAzi4B7ARglgxTKmNl0HWeYw30L0+OuNECoP/0g=,tag:Wz9FUcEhT723yvHTw6uS2Q==,type:str]
    INTERNAL_AUTH_SECRET: ENC[AES256_GCM,data:OtK+Pnq4YgYYOSeUu7VVuwps7ZHDgTtHU8uam2tD4FbBdgMyQhrOYrY8y+SHEvSoRAdqojMtDcPke4HFzQVQ3A==,iv:jMY3EXXPbkKTS6DUm1vfM9wyFnuMDzBDPb9KVOiIw8o=,tag:y8MtdyUn3wLM7Y1s6MvvEQ==,type:str]
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:BFwf20klif90iQ==,iv:2cv+/oph0tiCI1Xcs3e+YPH1NKkRCLaWuP6wTXiRzwg=,tag:bGh09BFaiUvNZRdW3zjcsA==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:y1uF8t3YXUs/fg==,iv:kEpHL0tD9qPjNr6nU+kif8WNpQ0uiqRFZ6Y/9NCNFag=,tag:LKtWKTJK05++s8r3I9/qiA==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:Wjcedw==,iv:fnAXDLdRxBJzDvlozerQlZdSA9OWsx4hupNIQLymAPU=,tag:R8l26pgU1PLyCYiwZ81Zvw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:5T6NdIKn9YcF1VITx4fhRCnrcs2B70vkLinSLd6WLQI=,iv:+whdfbrM4Ar32Zh4NqBJnib4p6zovufJXJoYuNZjdCM=,tag:trmteBHADMriV2aQKXpZuw==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:x8FaACxKk6T7,iv:5mPt7E1DM26TmErVMxKc89PDDBt3Hqn4QxPBuk1nAIw=,tag:7Y18aAg4uQ9R63kPUbTxsQ==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:LXef8YB8KLWoBQdtCJTU6Pb/m3hxjbAtkZe8cDToZ1Sw9uRQbA==,iv:XgzbzDYThLsxKPfxkLEbD3rsL3TFVcqxDrq6gCbIvAE=,tag:SiRbyH6Ou8hlJ6ve5Mv+mQ==,type:str]
    SIGNING_CERT_PASSWORD: ""
    SMTP_APP_PASSWORD: ENC[AES256_GCM,data:y993Fz0eegAeKPBykvW0km1qVg==,iv:D4i6amHYGXKZXNJjb+abjFse65GyUPgTOfRZzdBOWtQ=,tag:pmAzUI4iR7cFt1yuk3JMoQ==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:8PVF4fGJUOdXFRqju3nPCco9,iv:lh+VIvDiQKXsddtwtJSVxBlCmEsSjhuMiqcP06Z6o1Q=,tag:gmXmGzZFVUXgF4sZSuzLXQ==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaUlRLeEw2MkZEL3NLN0Ew
            SU5WRndVSVVTVE8yU2t0NCsvMjlGVXZqUDJnCm1lazZkL2Y1OUZmQXZmQy9IZk5J
            Z3B4a0I5cHQzeE93cXFMMzFsLzBaOFUKLS0tIHN2TEh0amlkRmZRa0lGb1p3ZHJN
            alhPN0JjUEdJaFZuUmQya0xvb1RVNzgKPJOMeRViW8zHH/0uqmjNF4fJTlDTrtO1
            A7dDnwEp3b8ZsWKvHUdTn6vkezVFYMNFHH1tLwz3sKk/L81CCjVA8Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5wsguw34gmnnllle8qzcjvjkl22e88em3a0lseqs0l9lscmr5pqsg6gyn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTS25JWUVqUEc2ci9aVHI1
            SWJRejMyUUhoSk5BLzhCaHp5N2FYenYrY0N3CnA5d2JZRDNKclV1c2M5MVpic1dV
            amwxQnhZcHlJaVhPVHoyQ3BVdjUyQncKLS0tIGlhajJ6TVpaM3VYaTV1ZzhjMHMx
            ZEZyeS9CL080eURxakQ3d1lqek1tZDAK/JtP4usHCSCe1aF5aznfx0ll67avhT1i
            QgaMW8lUFtIqU4BALBtqaniygp/9TcOpn2TXDGUBmKGFC+Yns9yuXw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13yvwrz6cvg8cwq78m6jvy9mndjdyuv0k3kh0du72v28puqcuafms8p28gr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-28T20:40:38Z"
    mac: ENC[AES256_GCM,data:nldPZnnMfCCwEfSc8rUXA6diVJtOLHaEwp6fgU4QriXnckf5GzjnlbtbiBX3/QuP71V8h2UlW4cA3Mo+q0UOQsenjMXYdwttxTlniBGseZNMVrBZByIzdguAka9ykD+hVj0H6yl9qJtt6/HB6gsg5poeK0QCSklWqsNJt5u5avE=,iv:Jz86YcrE9lWmsbiyaBdMazBsEC/moFHwTQeRIXjFBzo=,tag:fvUZ//jhGbnrGDWmQhxYtA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        argocd.argoproj.io/sync-options: Delete=false,Prune=false
    name: auth-env
    namespace: vcap-dev
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:Rfrwwo/DaptB0ykar9J1QaQ5wsVnOfA6vA8RmMKAtE0JyR9WOuDBmjjDuRrpMVtoEfNEpk7yOutwHnF2okF+SEzeo3SxXyiJbbD4GmlfI/Ru0lwT8xGskv1SEdAMLFwi6Jku,iv:jM4Tmm1LE5V44gkQB/10nrjXXB/f9tLZRGzshMGPUsc=,tag:h9Q6WIZF0/YBr8LPxn3Wkw==,type:str]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:Mnpq9yvbnn81DRRw6nGuEBxROTskhYyQOr181ivpNzZvpIL9llU9gIUdX2cAGM5s1NQ0cdH1THgCm3QMjQ27YAjRpky5LhzU,iv:zyApjUUy0kLZXQEeNTR46TkPYycX0B+NADW5IjRQ/v8=,tag:0uSBWRI7lEUbcZlsrGJPIg==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:YVeGJsjGf6zy4VecubRwHlG1qNbcUDGLNGu9ts5zvU/WXdQ=,iv:vPrUgk4JqxcucdXFoX4Wy1woBusEGyJNYozySOEN+aM=,tag:WegiMasB6WVre4p/G6/e7g==,type:str]
    INTERNAL_AUTH_SECRET: ENC[AES256_GCM,data:2xeKDmKNe9WrkmhRLFaOAPllSQw0FO3tfsjAXrdn+0EpqbEcEEdxZ1mhBIiIFFOE+mQNG/uvkfX4UeVFCoen4w==,iv:Vh632JEejIy/Zz3E6wFzxQterAF8Pp3o6iQuRzMsPFg=,tag:9hbpyhAGoEwUcwxWKemzLw==,type:str]
    JWT_SECRET_KEY: ENC[AES256_GCM,data:V6RH1OrQSR6wG1u/VP9APTEXoirEkvLrflRFXEkiYjDyCY1DWFKJy5lz28qXgv+zqkIvdL6Y3oyCA2NrCoVCVA==,iv:+M40OQ/jqwHNTGX/0vDM3Xtp4PqEwYGpVqsxwzwU2qY=,tag:mPOBU0bDG6TY8XfJMs+XDw==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:sI+T/ntVjlwYDNxP2MadsUAbi0xIsXBr/cQCZ3EWAzYLt8W2ww==,iv:wIbLW4ZWdYn9HB6iX9Uh5rbnd5QYkInz4opxyYYExgg=,tag:1ZgkBK9rJkr5D80kYZMRiw==,type:str]
    SMTP_APP_PASSWORD: ENC[AES256_GCM,data:UtSGZ5lhz5CrT0QSUAYnqEI9SQ==,iv:BzSGhfu/i9ofamcBIJ1IBt2sAdylBsuhRWHNu5RyONk=,tag:wgtsuKqXo387AalOHAARfA==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:lfocngLSQcwDyhDKkxxQoQ2e,iv:KfU86WgGQDuHlPDhdju2HQLqcxKlDvu08KWhtf0pem0=,tag:TXm1hYfUvEcSlx0+NoiaAA==,type:str]
    TOTP_ENCRYPTION_KEY: ENC[AES256_GCM,data:hXdUVADAF68BSX21thTAScie5S2YzLKlIZnmDpy7hxvkVvYiaaJzzbv+iIGNzR0XTFtz46rLE+BFZWhR5s7ngQ==,iv:OJZ6lRbUsz2EOd+oC7xQlGFDjGGROecWJ05MO2H6GbA=,tag:nR6bmdjKO/DKw+W7SC2XZw==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaUlRLeEw2MkZEL3NLN0Ew
            SU5WRndVSVVTVE8yU2t0NCsvMjlGVXZqUDJnCm1lazZkL2Y1OUZmQXZmQy9IZk5J
            Z3B4a0I5cHQzeE93cXFMMzFsLzBaOFUKLS0tIHN2TEh0amlkRmZRa0lGb1p3ZHJN
            alhPN0JjUEdJaFZuUmQya0xvb1RVNzgKPJOMeRViW8zHH/0uqmjNF4fJTlDTrtO1
            A7dDnwEp3b8ZsWKvHUdTn6vkezVFYMNFHH1tLwz3sKk/L81CCjVA8Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5wsguw34gmnnllle8qzcjvjkl22e88em3a0lseqs0l9lscmr5pqsg6gyn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTS25JWUVqUEc2ci9aVHI1
            SWJRejMyUUhoSk5BLzhCaHp5N2FYenYrY0N3CnA5d2JZRDNKclV1c2M5MVpic1dV
            amwxQnhZcHlJaVhPVHoyQ3BVdjUyQncKLS0tIGlhajJ6TVpaM3VYaTV1ZzhjMHMx
            ZEZyeS9CL080eURxakQ3d1lqek1tZDAK/JtP4usHCSCe1aF5aznfx0ll67avhT1i
            QgaMW8lUFtIqU4BALBtqaniygp/9TcOpn2TXDGUBmKGFC+Yns9yuXw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13yvwrz6cvg8cwq78m6jvy9mndjdyuv0k3kh0du72v28puqcuafms8p28gr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-28T20:40:38Z"
    mac: ENC[AES256_GCM,data:nldPZnnMfCCwEfSc8rUXA6diVJtOLHaEwp6fgU4QriXnckf5GzjnlbtbiBX3/QuP71V8h2UlW4cA3Mo+q0UOQsenjMXYdwttxTlniBGseZNMVrBZByIzdguAka9ykD+hVj0H6yl9qJtt6/HB6gsg5poeK0QCSklWqsNJt5u5avE=,iv:Jz86YcrE9lWmsbiyaBdMazBsEC/moFHwTQeRIXjFBzo=,tag:fvUZ//jhGbnrGDWmQhxYtA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        argocd.argoproj.io/sync-options: Delete=false,Prune=false
    name: pull-secret
    namespace: vcap-dev
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:fMO7ACQUSI6znxeOkxWl9V92I7Ev8RGXZNkjim6/+f8A/VDsmrNT6Jzldvs6l6d73qJCCBQABDdTYNOSeGrH9xIlYvVE0JpIy6JqdAvBvXK0+fsDoWHi2IMgWxQVVulyKVvSL5hQOXsN5lLqJjZUuYfwDht07K0aNVDpqVsyocPmtlsSq2RTIl9TPcUBpcJWwBu3mgw7x0OzK4/NyoHAXdPLfxzPiLFsNXFwcItI9nxqsdls4tLW4m9Iu/xpdfXVUAA9kG7w,iv:TcLyoRRocSNZv6jdd9+qcKiJg4EABn6+oeCr9taQhyw=,tag:Kg2qaJk5ARylKsQ4hdD4DQ==,type:str]
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaUlRLeEw2MkZEL3NLN0Ew
            SU5WRndVSVVTVE8yU2t0NCsvMjlGVXZqUDJnCm1lazZkL2Y1OUZmQXZmQy9IZk5J
            Z3B4a0I5cHQzeE93cXFMMzFsLzBaOFUKLS0tIHN2TEh0amlkRmZRa0lGb1p3ZHJN
            alhPN0JjUEdJaFZuUmQya0xvb1RVNzgKPJOMeRViW8zHH/0uqmjNF4fJTlDTrtO1
            A7dDnwEp3b8ZsWKvHUdTn6vkezVFYMNFHH1tLwz3sKk/L81CCjVA8Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5wsguw34gmnnllle8qzcjvjkl22e88em3a0lseqs0l9lscmr5pqsg6gyn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTS25JWUVqUEc2ci9aVHI1
            SWJRejMyUUhoSk5BLzhCaHp5N2FYenYrY0N3CnA5d2JZRDNKclV1c2M5MVpic1dV
            amwxQnhZcHlJaVhPVHoyQ3BVdjUyQncKLS0tIGlhajJ6TVpaM3VYaTV1ZzhjMHMx
            ZEZyeS9CL080eURxakQ3d1lqek1tZDAK/JtP4usHCSCe1aF5aznfx0ll67avhT1i
            QgaMW8lUFtIqU4BALBtqaniygp/9TcOpn2TXDGUBmKGFC+Yns9yuXw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13yvwrz6cvg8cwq78m6jvy9mndjdyuv0k3kh0du72v28puqcuafms8p28gr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-28T20:40:38Z"
    mac: ENC[AES256_GCM,data:nldPZnnMfCCwEfSc8rUXA6diVJtOLHaEwp6fgU4QriXnckf5GzjnlbtbiBX3/QuP71V8h2UlW4cA3Mo+q0UOQsenjMXYdwttxTlniBGseZNMVrBZByIzdguAka9ykD+hVj0H6yl9qJtt6/HB6gsg5poeK0QCSklWqsNJt5u5avE=,iv:Jz86YcrE9lWmsbiyaBdMazBsEC/moFHwTQeRIXjFBzo=,tag:fvUZ//jhGbnrGDWmQhxYtA==,type:str]
    version: 3.13.3
