apiVersion: v1
kind: Secret
metadata:
    annotations:
        argocd.argoproj.io/sync-options: Delete=false,Prune=false
    name: backend-env
    namespace: vcap-dev
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:PfT2+24OSeIsweExm5XfzZjwA/JGUqLUs1TCIsRxaN6eIv7bf1WjBHwxkxZ2WBOlhp8K0EeEz0ZwPLHsU9O9Q8OLphtQncWYdoDR5uAFpcG9bUubPzt5B9/CsYZuelK0Gvs=,iv:zm0Nn1SmEozWFqakkFYLBRFZfkVCWA9z8ciuIS0hPvs=,tag:R86JvRJCxOcyKoGVEelFKg==,type:str]
    DATABASE_URL_SYNC: ENC[AES256_GCM,data:d0JJqTj2NUFOA8Z7vIZYCWFuT06V0I55i2KqSHVEv3X39L6f7OfWNKxc8+WBm819pgalwVkFfwjAZJ/DSzE/U7Jy5zaFBZqUS563S4JLNH8xUq43bEgplUtFpS+u+YOWWf0=,iv:3sRAH+fBFcQKJonC0qa1GH4mPRoYrbqvuwJTOj9WJ6U=,tag:2cVcwdNPO7W9q1TsBRwlXg==,type:str]
    INTERNAL_AUTH_SECRET: ENC[AES256_GCM,data:8EKo/ozqDM4On40QYzGNPY3DyMkdA01fyJgOE4Z9OTqIkjybsybzqA6k10Q+gRHSwuYe33TH2gZbMhp8xJR5zA==,iv:AR32TYVaASzsHqq0Z9zxEz/WLgnVvsVG5Pr2wDMF50E=,tag:lpF1sekNcH/eu7rHMfyaEg==,type:str]
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:aGpj1PtE+IHJ6g==,iv:u5123m3dYmdDYGMaWklIra/iw00tcmv3b3CLjafVHEk=,tag:MWoasovh/MQHbfaAGwIoDg==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:7bxxp9iXQQnBUw==,iv:hUreu2Jf1VCXYDxMxgEOlKdmVxo5l6gaXGOyAGnsB+8=,tag:njJqPKLz+YTWTDJfki1rZw==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:5JOYsw==,iv:u4RRVCWHt/5TGiLvAjD+uaPq1lDjj0eJ81qiJ3pOBBE=,tag:ciXIr5m6MFDh8CHRNHpoQg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:tuTPerv5sIo+DAyaeyIo0R2oUemBXJgL6Jg+lvGVJc0=,iv:FcqMquN/6pOobA89ryw+f0pnza+JAyvAOKQR2NOEwXI=,tag:cld5t8aKNecDWmIKR9bTYg==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:7+gQ4dAgypqh,iv:dJUgmtqRzB3LP45ZUjTa/oNo2IVtfVRbjhkO+i0K2Go=,tag:jgmsnZQvniNUjlWOGTxisg==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:vDyjXWoUjY8ntsUltZYSBkZnJAzYAeFpoG3eZjOd4NqN6JBxIQ==,iv:VRFpLbAyf7XWR8it40jAP48tzEB5g89m5YdnIlQJPlE=,tag:4KtMLtStwiIO0JjKh6YS4Q==,type:str]
    SIGNING_CERT_PASSWORD: ""
    SMTP_APP_PASSWORD: ENC[AES256_GCM,data:uBl+M+F/4x4/eKDL0QCeO4+Zpg==,iv:lr/6RU0n2pVjkc3mi8j/JwOe9Q9LpmIxUOw0a5Q/zXY=,tag:7uCQ3fApWgHJ+J9dVbINrA==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:NyJmosgBn4s//G5o444UevhL,iv:uTpfWWTrUAzcANK6ri3ohQ24h5qU6vZunRMlbBLhk7o=,tag:11/NPrVo9xWSUqEYAO/7Pg==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOQ3FkTlRqOVVmNWlQbm9m
            TCtJZE8rTEZkTktHT25iY3lxRVZIYU9wRUJjCldoWVdvTk43bUlFZVk5U2NRQXJS
            U0xqNzBYVHA0U2hGdGxWd2FaWHJmV0kKLS0tIDk0Y0V2TmJVYkdtY25OWU9xK3lt
            YUEwZlRIU1E5YjhRa3oxY2FoNjY2dEUKoamilOgI+LhT56PDMI4Vkle97lJjLpMS
            9nS3NRYTS4wsI+fTTznsIJZg2fBRf5i0GFQ6vucGLrFGbGH7MNsqXg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5wsguw34gmnnllle8qzcjvjkl22e88em3a0lseqs0l9lscmr5pqsg6gyn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwdUY2aEwvNkRGTFFyaXl3
            TGMzRU42b21TaWNuS1M0L0k0V0oxN210TnljCmJXVUFDb1JFT3ZRMkdtQVkzTXcy
            ckxuQzBhSWNXSEZrK0M3ckFZQytyNTAKLS0tIHpzbUhITWJSV04zaDB6Nm9zZGVH
            Y29KRnJMWk5wYUl0bEphTHZxaU5aczQKxsJcCddQcyrWDX6ox0tby5dGJDhYHBrQ
            2A6x4BUeUbDt7aDBaYZgGuMAivWPjrj+PbjFpKXDRI2dnXO3qniulw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13yvwrz6cvg8cwq78m6jvy9mndjdyuv0k3kh0du72v28puqcuafms8p28gr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T17:35:39Z"
    mac: ENC[AES256_GCM,data:zJynJyVvo0/HoV41n5B51+XjjrcRkzMkCZESYCuNJReE5BODFdcDjcuW/2c/JysbA8Qyj5qOz/K3MWHpdf6g/veE5ElUQwnHhEVjeIisKOc1C2bX9y+T4dLR2BBj9HsZuxyiz8RAwkD8sBJlkn/Y+7WkjR7DTgeL8XX77rOU8b8=,iv:PTSECBVyh6ApB/MagtpsRwR6Ljd3q5WRGTl9dMUU2MU=,tag:co6lkgxwn2tYF8A+CuZb2Q==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        argocd.argoproj.io/sync-options: Delete=false,Prune=false
    name: auth-env
    namespace: vcap-dev
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:oT3rQHoaYv0z2ETSac2Kzk22ideywC9Eqi/Zj1R4ztfH6P5fUF+4dIVbqHgiYZ1se0ae8vnF8KRVLYI6UaFVhXlK9jNmVOlvQ49QQo+DLx3B3v2lIuSm2CMVBVKBbPo7Df0=,iv:JLJgp/sy6jVpaLYxmoIL22RVh4mSFelsa2QCU31Nxzg=,tag:K0lDAhNyT05+DPRnV5Ntug==,type:str]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:zO2K2OQuUJmQvUYh90zLMWO/k/sRN5nCBkfgX+SpLosozkM02NGgUaGUcpNVnW3oEPghu11DhGEX1w9DBRxOJYsgDMfyQQxn,iv:2xbLSgB7vwLMdyAJVbtLLLG8/b1sD3wkjp+y0ouJOWg=,tag:P1ODjdsNP/PF/9TrCETgfg==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:eZBcO55S6GvzlzRE0kiwiBtrK9E2qdkkBk2pEBZgb75zHpM=,iv:HZ3f4+hg0YvTcbchBZA5+TyUngjGtdhzKWAmk0fYlhE=,tag:LHIYZ3xq1TYgKeiRoz1lYQ==,type:str]
    INTERNAL_AUTH_SECRET: ENC[AES256_GCM,data:WB2XlEJkIlQZcemNwQq5bXel33bqxB7HeRCvY8q0RS+E4K00xRGudc+NkAlxtoiYqa2/n2ZCCqhgLq5ees65LA==,iv:OUDvTUvggNclOsjy2lACU3XrM1aDhl7RaArtOq/CudU=,tag:wprq/ROgHX6Cdyt63su7zg==,type:str]
    JWT_SECRET_KEY: ENC[AES256_GCM,data:4K+W+LFVumPax9f8AvI6LQ3M+jF/8mKWpAUpCN2Psy3KNayUnLG6PlIx8mKx+aGP1f5oc8ZxNv83/8mogRkj8A==,iv:jtFmgEjYVZHZn7lhcyqxw+/Xgg0uy3V+tphLHqObou4=,tag:HD3oIWTyw3gSypFefp9RhA==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:r4Sr/bB7LgrtbOY9bmZXOZAkH877LjNT7uvRwhPOz96ZTvCvrQ==,iv:iQBZ39N+VMWiv+agW8Tolqp2dbjPetogc1SVD8Yeb5I=,tag:GF59MgjLMeMgpQtZVL4OwQ==,type:str]
    SMTP_APP_PASSWORD: ENC[AES256_GCM,data:W9ukFJ1sF0j4tAwxyyZ3puPYPQ==,iv:tpCtDx5jqbTn8qKO3b9jT3BPTNcFiSaSo8yJwcU6YhU=,tag:FZa+s3enUajp1yG7wkTYHQ==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:atnIZDImuF3y9eoJ8uTDj+Cz,iv:DYnf9UlwtmFe1clkFqBPWwUQrZB1n4ECY72vjhgZ1a4=,tag:YlUAcMvRfcGQ0V0SLe2VZA==,type:str]
    TOTP_ENCRYPTION_KEY: ENC[AES256_GCM,data:TAgLkmbfagGb1YQPYHH9qr93r8PKBKnt3i+hYfG8ftRg3UhUE8r80ep2ivqYLPQ6sfl2DnV35iVoQoRhc0y+iQ==,iv:kKMgaksRqloB2WoXDc9JXXLfvZfZjEA6dFDx8C2+vvY=,tag:Jlnpfuxe5t4J3UhpV2lvAA==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOQ3FkTlRqOVVmNWlQbm9m
            TCtJZE8rTEZkTktHT25iY3lxRVZIYU9wRUJjCldoWVdvTk43bUlFZVk5U2NRQXJS
            U0xqNzBYVHA0U2hGdGxWd2FaWHJmV0kKLS0tIDk0Y0V2TmJVYkdtY25OWU9xK3lt
            YUEwZlRIU1E5YjhRa3oxY2FoNjY2dEUKoamilOgI+LhT56PDMI4Vkle97lJjLpMS
            9nS3NRYTS4wsI+fTTznsIJZg2fBRf5i0GFQ6vucGLrFGbGH7MNsqXg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5wsguw34gmnnllle8qzcjvjkl22e88em3a0lseqs0l9lscmr5pqsg6gyn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwdUY2aEwvNkRGTFFyaXl3
            TGMzRU42b21TaWNuS1M0L0k0V0oxN210TnljCmJXVUFDb1JFT3ZRMkdtQVkzTXcy
            ckxuQzBhSWNXSEZrK0M3ckFZQytyNTAKLS0tIHpzbUhITWJSV04zaDB6Nm9zZGVH
            Y29KRnJMWk5wYUl0bEphTHZxaU5aczQKxsJcCddQcyrWDX6ox0tby5dGJDhYHBrQ
            2A6x4BUeUbDt7aDBaYZgGuMAivWPjrj+PbjFpKXDRI2dnXO3qniulw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13yvwrz6cvg8cwq78m6jvy9mndjdyuv0k3kh0du72v28puqcuafms8p28gr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T17:35:39Z"
    mac: ENC[AES256_GCM,data:zJynJyVvo0/HoV41n5B51+XjjrcRkzMkCZESYCuNJReE5BODFdcDjcuW/2c/JysbA8Qyj5qOz/K3MWHpdf6g/veE5ElUQwnHhEVjeIisKOc1C2bX9y+T4dLR2BBj9HsZuxyiz8RAwkD8sBJlkn/Y+7WkjR7DTgeL8XX77rOU8b8=,iv:PTSECBVyh6ApB/MagtpsRwR6Ljd3q5WRGTl9dMUU2MU=,tag:co6lkgxwn2tYF8A+CuZb2Q==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        argocd.argoproj.io/sync-options: Delete=false,Prune=false
    name: pull-secret
    namespace: vcap-dev
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:j0aNVt1NWRiGjhA2TTzfOgwUGe148Rt285dle1XPDZKyIjTvgTyt8QAxrGkU/ohOvyvnk/mpu2uUYtJPRfzQ6bCx/v6pRZyHLXO/O8FSv+cF+/HHGM0KNMjl/00wTVCwo3JOSm6Q03SXllZzbVhLMHoxdB8FAaCaY0RJIKiasbdNOsi/oLkr88gvvRPsh7giCsAZHLnMrmUakBOfVMrXEi9VSCkG+IOg57leJW720qz0sCBoMw2FSvSsStzEkzgnV2CiNuNe,iv:28o7msMjrE5+jIQpEaXc46FCNtmYpeRHiBJQU013xyA=,tag:AKnx/hHqHB7J0B+DwYLU5w==,type:str]
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOQ3FkTlRqOVVmNWlQbm9m
            TCtJZE8rTEZkTktHT25iY3lxRVZIYU9wRUJjCldoWVdvTk43bUlFZVk5U2NRQXJS
            U0xqNzBYVHA0U2hGdGxWd2FaWHJmV0kKLS0tIDk0Y0V2TmJVYkdtY25OWU9xK3lt
            YUEwZlRIU1E5YjhRa3oxY2FoNjY2dEUKoamilOgI+LhT56PDMI4Vkle97lJjLpMS
            9nS3NRYTS4wsI+fTTznsIJZg2fBRf5i0GFQ6vucGLrFGbGH7MNsqXg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5wsguw34gmnnllle8qzcjvjkl22e88em3a0lseqs0l9lscmr5pqsg6gyn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwdUY2aEwvNkRGTFFyaXl3
            TGMzRU42b21TaWNuS1M0L0k0V0oxN210TnljCmJXVUFDb1JFT3ZRMkdtQVkzTXcy
            ckxuQzBhSWNXSEZrK0M3ckFZQytyNTAKLS0tIHpzbUhITWJSV04zaDB6Nm9zZGVH
            Y29KRnJMWk5wYUl0bEphTHZxaU5aczQKxsJcCddQcyrWDX6ox0tby5dGJDhYHBrQ
            2A6x4BUeUbDt7aDBaYZgGuMAivWPjrj+PbjFpKXDRI2dnXO3qniulw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13yvwrz6cvg8cwq78m6jvy9mndjdyuv0k3kh0du72v28puqcuafms8p28gr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T17:35:39Z"
    mac: ENC[AES256_GCM,data:zJynJyVvo0/HoV41n5B51+XjjrcRkzMkCZESYCuNJReE5BODFdcDjcuW/2c/JysbA8Qyj5qOz/K3MWHpdf6g/veE5ElUQwnHhEVjeIisKOc1C2bX9y+T4dLR2BBj9HsZuxyiz8RAwkD8sBJlkn/Y+7WkjR7DTgeL8XX77rOU8b8=,iv:PTSECBVyh6ApB/MagtpsRwR6Ljd3q5WRGTl9dMUU2MU=,tag:co6lkgxwn2tYF8A+CuZb2Q==,type:str]
    version: 3.13.3
